misc/fstab

Nice for btrfs. (auto is already used on /dev/xvdi.)

Mount /dev/xvdb with fs type "auto"

---

debian/control

qubes-core-agent `Depends:` on `iptables-persistent`. (https://github.com/QubesOS/qubes-core-agent-linux/blob/ea0615d4da0ce9f06dc0ce8fe918a3c39df59c39/debian/control#L12)
Is this necessary?
It causes an usability issue on suite upgrades.
How to manually trigger:
```
sudo apt-get install --reinstall iptables-persistent
```
Causes a very difficult questions for users.
```
Package configuration                                                                                                 
┌───────────────────────────────────────┤ Configuring iptables-persistent ├───────────────────────────────────────┐  
│                                                                                                                 │  
│ Current iptables rules can be saved to the configuration file …
```

removed iptables-persistent from Depends to improve usablity

---

qubes-rpc/qfile-unpacker.c

When qfile-unpacker's child encountered an error, it would display an
error message and exit(1), but the parent didn't inspect its status and
exited successfully.
That was unfortunate for qvm-move-to-vm: Even if the destination VM e.g.
didn't have enough free disk space, the RPC call would claim to succeed
anyway, so the file would be deleted from the source VM.

qfile-unpacker: Avoid data loss by checking for child errors

---

qubes-rpc/qubes.GetAppmenus

qvm-sync-appmenus fails when a shortcut have spaces in the file name #1657

Proposed solution for issue #1657

---

qubes-rpc/qvm-run

-Properly quote variable names.
-Properly handle empty domain name.
-Print usage information to stderr.
-Follow coding guidelines WRT tabs/spaces.

Improve qvm-run

---

qubes-rpc/qvm-copy-to-vm

Should have been part of #10, otherwise qvm-move-to-vm won't remove the files after copying. Sorry about that.

Remove exec in last line of qvm-copy-to-vm

---

vm-systemd/qubes-misc-post.service
vm-systemd/qubes-netwatcher.service
vm-systemd/qubes-network.service

Network management software should order itself after network-pre.target
(man 7 systemd.special) so that other units can order themselves before
the *beginning* of network initialization. (qubes-misc-post too because
it calls setup-ip.)
Relevant for QubesOS/qubes-issues#2108

Order network management units after network-pre.target

---

vm-systemd/qubes-misc-post.service

`qubes-setup-dnat-to-ns` is called multiple times during boot.  Of particular interest are the two invocations done by:
1. `/usr/lib/qubes/init/network-proxy.setup.sh` (`qubes-network.service`)
2. `/usr/lib/qubes/init/misc-post.sh` (`qubes-misc-post.service`)
These can, and do often, run in parallel.  Often enough that the `PR-QBS` `nat` chain can end up with eight rules instead of four, or (worse) zero rules.
This commit represents the proper boot ordering of these services, where the post startup *must* happen after Qubes has already started its iptables, firewall, network setup and netwatcher.
This eliminates the race.
I considered wrapping the execution of `qubes-setup-dnat-to-ns` in a `flock` exclusive lock to prevent the race, and that may still be a good idea to do, but the actual …

Eliminate race condition with qubes-setup-dnat-to-ns

---

init/functions
init/setup-dvm-home.sh
init/setup-rw.sh
rpm_spec/core-vm.spec
vm-systemd/mount-dirs.sh

When DVM savefile creation process starts, we initialize the DVM /home_volatile/user with the files from /etc/skel or /home.orig/user (depending on which one exists) unconditionally.

Initialize home_volatile for disposable VMs.

---

Makefile
debian/qubes-core-agent.postinst
vm-systemd/haveged.service

QubesOS/qubes-issues#2161 - 
Issue arises in both stretch and xenial. Solution is to provide override file, changing ordering of startup.
Reenable haveged.service after Debian package installation, to force new link in multi-user.target.wants after upgrade.

Add systemd override for haveged in xenial and stretch. 

---

archlinux/PKGBUILD

The Arch build was failing due to missing the init folder. Adding init to the list of sources to be linked makes the build pass. Should fix the bug experienced here:
https://groups.google.com/d/msg/qubes-users/_y8tjPeynbg/NScRKRAdEAAJ

Copied needed sources to build root

---

Makefile
debian/qubes-core-agent.postinst

QubesOS/qubes-issues#1108
The prevention of previews is already set in Fedora packages.
This applies it to Debian packages too.

Apply gschema override preventing previews in nautilus in Debian

---

vm-systemd/bind-dirs.sh

Tested on: Qubes OS 3.2; Debian 8 TemplateBasedVM (and Template)
Ping: @adrelanos

bind-dirs: Fix handling of binds containing spaces, fix shellcheck warnings

---

network/qubes-setup-dnat-to-ns

As per discussion in QubesOS/qubes-issues#2674

If there is only 1 DNS server make both DNAT rules point to it

---

network/network-manager-prepare-conf-dir

Qubes-specific options must be added in NetworkManager.conf, even if
those lines are commented out by default. The problem is solved by using
extended regular expressions.
Fixes #2584

network: Properly handle comments in NetworkManager.conf (#2584)

---

misc/qubes-download-dom0-updates.sh

Few reasons for this:
1. new templates use dnf to download packages, so yum.conf is unused
2. dom0 in Qubes 4.0 don't have this file at all (so sed fails here)
3. $OPTS already contains --setopt=reposdir=...
Fixes QubesOS/qubes-issues#2945

dom0-updates: do not modify yum.conf

---

archlinux/PKGBUILD
archlinux/PKGBUILD.install

Without this change the package builds successfully but there is a file conflict error when installing it. This is because the default value for `SYSTEM_DROPIN_DIR` in the [Makefile](https://github.com/QubesOS/qubes-core-agent-linux/blob/a7ef5726ed368b97acb2f6497dece22ca9f9fdd3/Makefile#L55) is `lib/systemd/system`, however `/lib` is a symlink to `/usr/lib` in archlinux. I do not know how the [package](http://olivier.medoc.free.fr/archlinux/current/qubes-vm-core-3.2.18-11-x86_64.pkg.tar.xz) in the [repository](https://github.com/QubesOS/qubes-core-agent-linux/blob/a7ef5726ed368b97acb2f6497dece22ca9f9fdd3/archlinux/PKGBUILD#L92-L94) is not broken. When building this myself, there's a `lib` folder in the package root that conflicts with the symlink.
Also, I am not sure what the purpose of …

Fix the archlinux package - DROPIN dirs, shellcheck issues, indentation

---

archlinux/PKGBUILD-qubes-noupgrade.conf

Some pacman wrappers like powerpill will fail to parse the config file when the options are not sectioned correctly:
```
pycman.config.InvalidSyntax: unable to parse /etc/pacman.d/10-qubes-noupgrade.conf, invalid key for repository configuration: 'NoUpgrade = etc/pam.d/su'
```

archlinux: add correct section to qubes-noupgrade.conf

---

Makefile
debian/qubes-core-agent.install
init/resize-rootfs-if-needed.sh
misc/resize-rootfs
qubes-rpc/qubes.ResizeDisk
rpm_spec/core-agent.spec
vm-init.d/qubes-core-early
vm-systemd/75-qubes-vm.preset
vm-systemd/qubes-rootfs-resize.service

Implement resizing of root filesystem when it is the last partition.
This handle both online (qubes.ResizeDisk service) method and offline (resize
on domain startup).
Fixes QubesOS/qubes-issues#3173
QubesOS/qubes-issues#3143

Handle resize of root filesystem with new partition layout

---

misc/qubes-download-dom0-updates.sh

Since the qubes-download-dom0-updates script executes dnf with fakeroot, some dnf plugins like etckeeper break the update with "Permission denied" errors.

Disable dnf plugins when downloading dom0 updates in sys-firewall

---

Makefile
Makefile.builder

4.0 template builds use `<package>.install` files with dh_install.  The
differences between Debian and Ubuntu packages also need to be represented
in these files.

Fix Ubuntu template builds

---

network/update-proxy-configs

I was getting more errors than expected when updating the template and it was because I'd used an HTTPS pacman repository. [This](https://curl.haxx.se/docs/manpage.html#ENVIRONMENT) is the curl documentation on proxy configuration. I tested the change with my template and it worked.

Fix the Archlinux template update proxy to work for HTTPS URLs as well

---

rpm_spec/core-agent.spec

For R4.0, where `iptables[-restore]` is still used by `vif-route-qubes`, `qubes-setup-dnat-to-ns`, and `iptables-updates-proxy`.

Add iptables dep to qubes-core-agent-networking RPM spec

---

Makefile
debian/qubes-core-agent-networking.install
network/80-qubes.conf
network/ip6tables-enabled
network/qubes-iptables
network/setup-ip
network/vif-route-qubes
qubesagent/firewall.py
qubesagent/test_firewall.py
rpm_spec/core-agent.spec
vm-systemd/network-proxy-setup.sh

When /qubes-ip6 QubesDB entry is present, configure IPv6 address accordingly.
Same for /qubes-gateway6 entry. If IPv6 address is configured, load alternative
IPv6 firewall, which will actually allow IPv6 traffic.
If /qubes-ip6 entry is not present, behaviour should be unchanged.
Fixes QubesOS/qubes-issues#718

VM side of IPv6 support

---

qubes-rpc/qvm-copy-to-vm

`qvm-{copy,move}` run `qvm-{copy,move}-to-vm` with `$default` as the VM argument. Don't print the deprecation message in that case.

qvm-{copy,move}: fix spurious deprecation message

---

vm-systemd/75-qubes-vm.preset

It is responsible for the long start-up delay in Stretch template and is unnecessary. Testing confirms that sys-net templates continue to function as expected without it.(See QubesOS/qubes-issues#2913)
According to the docs, NetworkManager should be using dbus to connect with wpa_supplicant so this should be no loss.
Closes QubesOS/qubes-issues#2913

Disable wpa_supplicant@.service

---

network/update-proxy-configs

fixes https://github.com/QubesOS/qubes-issues/issues/3403

make apt-get apt-transport-tor broken in Qubes non-networked TemplateVMs

---

qrexec/qrexec-agent.c

Fixes QubesOS/qubes-issues#3433

qrexec: fix infinite loop when multiple services are waiting for GUI

---

network/80-qubes.conf

Debian templates currently have ip_forward set to 1.
This PR changes that default.
Closes QubesOS/qubes-issues#3453

Stop Debian templates from forwarding by default.

---

vm-systemd/bind-dirs.sh

`nullglob` must be active before a glob is used on a potentially empty directory. Call `shopt` immediately after the shebang line.
Fixes QubesOS/qubes-issues#3552

bind-dirs.sh: don't fail on empty configuration directory

---

network/qubes-nmhook

NetworkManager reports a bunch of events, reloading DNS at each of them
doesn't make sense and is harmful - systemd have ratelimit on service
restart.
Fixes QubesOS/qubes-issues#3135

network: reload DNS only on "up" event from NetworkManager

---

qrexec/qubes-rpc-multiplexer

Previously the script was called through shell as:
execl(shell, "-sh", "-c", "/usr/lib/qubes/qubes-rpc-multiplexer
...", 0);
This tells the shell to load login scripts, including /etc/profile.
Since 5512e4eadab846b52883b22c0160d36da60454b3 this is no longer the
case and the script is called directly. Since most services do expect
proper user session initialized (/etc/profile loaded etc), adjust the
script's shebang to behave like a login shell and load those startup
scripts.
Fixes QubesOS/qubes-issues#3615

qrexec: launch services in login shell

---

Makefile
archlinux/PKGBUILD.qubes-update-desktop-icons.hook
debian/qubes-core-agent.postinst
misc/dnf-qubes-hooks.py
misc/qubes-trigger-sync-appmenus.action
post-install.d/README
rpm_spec/core-agent.spec

Update dom0 about all applications installed, not only desktop files for
them. Update also supported features and other things advertised initially
at template installation.
Fixes QubesOS/qubes-issues#3579

Call qubes.PostInstall service to notify dom0 about all apps/features

---

vm-systemd/qubes-sync-time.timer

/cc @adrelanos, in case you want to disable the timer in Whonix with a drop-in.

Really enable qubes-sync-time.timer

---

Makefile
rpm_spec/core-agent.spec

Fix conflicting file /etc/dconf/profile/user between Qubes and CentOS dconf.
Can be backported to r3.2.
This solve the issue related in https://groups.google.com/d/msg/qubes-users/KujLPwDNYCE/sLTpMcT9CAAJ

Fix CentOS 0/5 (centos: fix conflict with dconf)

---

debian/qubes-core-agent.dirs

This dir was present in 3.2.22 but then got removed from the package. Missing that dir causes a problem for qubes-dom0-update that expects to find that dir existing.
Fixes: QubesOS/qubes-issues#3620

Fix qubes-dom0-update regression by restoring dom0-updates dir

---

Makefile

Add services to Makefile- absence prevented build
Closes QubesOs/qubes-issues#3712

Add missing services in Ubuntu templates.

---

doc/vm-tools/qrexec-client-vm.rst
qrexec/qrexec-agent-data.c
qrexec/qrexec-agent.h
qrexec/qrexec-client-vm.c

Add an option for custom vchan buffer size, to override default 64k (for
each direction). This is especially useful when the other side of
connection is MirageOS based, because of limited memory and default
grant table size (128 entries).

qrexec: add qrexec-client-vm --buffer-size option

---

qrexec/qrexec-fork-server.c

With the old code the addrlen argument were uninitialized on the first
call resulting in errors depending on the compiler behavior.

qrexec-fork-server: Always initialize addrlen argument of accept()

---

Makefile
debian/qubes-core-agent.install
misc/qubes-run-terminal
misc/qubes-run-terminal.desktop
rpm_spec/core-agent.spec

Requirement for pull request about to be submitted to qubes-desktop-linux-manager, to add "Run Terminal" option to the qui domains tray.
Probably comes in handy in other places as well (Marek pointed out the i3 repo has a similar thing).

Add misc/qubes-run-terminal to launch any available terminal emulator

---

qubesagent/firewall.py
qubesagent/test_firewall.py

I've run into an issue with incorrectly generated rules for IPv6. I
added some debugging code printing the generated rules and the
resulting error (see below). Turns out `reject with` expects `icmpv6`
rather than `icmp6`.
Tested with Fedora 27 and Debian 9.
```
--- generated rule ---
flush chain ip6 qubes-firewall qbs-fd09-24ef-4179--a89-15
table ip6 qubes-firewall {
chain qbs-fd09-24ef-4179--a89-15 {
ip6 daddr fc00::/8 reject with icmp6 type admin-prohibited
ip6 daddr fd00::/8 reject with icmp6 type admin-prohibited
ip6 daddr fe80::/10 reject with icmp6 type admin-prohibited
accept
reject with icmp6 type admin-prohibited
}
}
--- output ---
/dev/stdin:4:36-40: Error: syntax error, unexpected string, expecting icmp or icmpv6 or tcp or icmpx
^^^^^
/dev/stdin:5:36-40: Error: syntax error, …
```

Qubes firewall: correct syntax for icmpv6 rejects

---

misc/uca_qubes.xml
qubes-rpc/dvm2.h
qubes-rpc/gui-fatal.c
qubes-rpc/qfile-agent.c
qubes-rpc/qfile-unpacker.c
qubes-rpc/qopen-in-vm.c
qubes-rpc/qvm-actions.sh
qubes-rpc/qvm-dvm.desktop
qubes-rpc/qvm-open-in-dvm
qubes-rpc/qvm-open-in-vm
qubes-rpc/qvm_dvm_nautilus.py
qubes-rpc/vm-file-editor.c

Implement option to disallow (ignore in fact) modifications of file opened in
another VM (including DispVM). This adds qvm-open-in-(d)vm --view-only option
and also replace 'Open In DisposableVM' option with two new:
- 'Edit in DisposableVM'
- 'View in DisposableVM'
Fixes QubesOS/qubes-issues#1118

qvm-open-in-vm: implement --view-only option

---

misc/fstab
vm-systemd/mount-dirs.sh

This is a twin PR. Please also see the PR in qubes-linux-template-builder https://github.com/QubesOS/qubes-linux-template-builder/pull/12.
This PR along with its twin changes `/usr/local` from a symlink to a bind mount similar to how `/home` is mounted.
I stumbled upon this because the sandbox in the opam package manager does not mount `/rw/usrlocal`. This meant that `/usr/local` was a dead symlink and that binaries in `/usr/local/bin` was not in PATH inside the sandbox. See https://github.com/ocaml/opam/pull/3446.

bind mount /usr/local

---

qubes-rpc/qvm-copy-to-vm

Added more descriptive usage text to the
qvm-copy/qvm-move/qvm-copy-to-vm/qvm-move-to-vm family of tools.
Also fixed bug that removed the file being moved for qvm-move-to-vm,
but not for qvm-move.
fixes QubesOS/qubes-issues#3529
fixes QubesOS/qubes-issues#4020

Add proper help text to qvm-copy tools and fix incorrect behavior for qvm-move

---

Makefile.builder

This effectively reverts the commits in https://github.com/QubesOS/qubes-core-agent-linux/commit/80b5c942069710f75aa7faea141e31c1cba60b33 and https://github.com/QubesOS/qubes-core-agent-linux/commit/54867b6eabed3a6dca0e932ff77f67aedfe43e03 which now prevent Xenial (and later) templates from being built.
There's no reason why those control files should not be installed.
Closes QubesOS/qubes-issues/issues/3871

Install qubes control files for services in Ubuntu templates

---

misc/qubes-run-terminal

`which` is an external tool, `type` is a shell builtin. Using the latter shaves off a bit of latency.
Also use the already open stderr file descriptor for redirection.

misc/qubes-run-terminal: which -> type

---

qrexec/Makefile

Closes QubesOS/qubes-issues#4261

Install Debian version of qrexec pam in Ubuntu templates

---

vm-systemd/bind-dirs.sh

Previously, bind-dirs.sh had a bunch of `true comment goes here` style debug messages (no-ops). Presumably this was done because these messages are intended as debug messages and would only be displayed when calling bind-dirs.sh with xtrace enabled. However, this includes some fatal errors, which are necessary to debug why bind-dirs.sh is ostensibly not working. For example, I tried to mount /var/lib/docker, didn't realize it did not exist (as an empty directory) in my base template, and there was no journalctl output at all. After this change, journalctl will contain the (very helpful) error message.

Voice informational messages in bind-dirs.sh

---

debian/control

Mark xserver, xinit and x11-xserver-utils as Recommends.
Tested this for some time and everything seems fine in headless system.
Closes QubesOS/qubes-issues#4202

Remove qubes-core-agent Debian dependency on xserver

---

debian/control

Closes  QubesOS/Qubes-issues#4411

make iproute2 a dependency for Debian core-networking

---

init/resize-rootfs-if-needed.sh

It was just being compared the wrong way; the rest of these are cleanups. At least, assuming I understand the script right - `non_rootfs_data` is just supposed to be a small margin for error right? I.e. that's what's meant by "(almost) the whole disk"?
It took me a while to get that so I renamed the variable to make it clearer although I'm not sure the new name is _all_ that much better... happy to either drop that commit or amend it to something else.
Fixes QubesOS/qubes-issues#4553 (and improves VM boot performance a _lot_ in the process; it shaves several entire seconds off boot times which especially adds up when all autostart VMs are being brought up at dom0 boot)

FIx rootfs resize script

---

debian/control
rpm_spec/core-agent.spec.in

Qubes Manager's update button fails in strange ways without it.

Add XTerm as a dependency

---

qrexec/qrexec-agent.c
vm-systemd/qubes-qrexec-agent.service

Avoid race conditions with services ordered shortly after qrexec start.
Make systemd know when qrexec-agent is really ready to serve.
Fixes QubesOS/qubes-issues#3985

qrexec: add startup notification

---

Makefile
debian/qubes-core-agent.install
misc/marker-vm
rpm_spec/core-agent.spec.in

Make it easy for packages to detect Qubes VM.
Fixes QubesOS/qubes-issues#1963

Introduce /usr/share/qubes/marker-vm

---

qubesagent/xdg.py

This part of GIO library isn't suitable for short-lived processes (the
call is done asynchronously and may not reach the application before
qubes-desktop-run process is terminated). To fix this, implement dbus
activation manually, synchronously.
While at it, implement waiting for application to terminate (useful in
DispVM), by waiting for its dbus name to disappear.
dbus-python API isn't particularly nice, but don't switch to completely different
library as a stable update.
Fixes QubesOS/qubes-issues#2449

Implement D-Bus Activation of desktop files manually

---

vm-systemd/qubes-sysinit.sh

Conflicts with gui-agent-linux without https://github.com/QubesOS/qubes-gui-agent-linux/pull/34.

R4.1: Pass GUI domain id to GUI agent

---

network/vif-route-qubes

Detect if IPv6 is disabled in the kernel (like it is in Whonix Gateway)
and skip setting IPv6 in that case. Otherwise 'ip' call would fail and
since the script is with 'set -e', it would interrupt setting IPv4 too.
Log error message in that case anyway.
Fixes QubesOS/qubes-issues#5110

network: don't fail the whole vif setup if IPv6 is disabled

---

misc/resize-rootfs
patches.debian/0001-Revert-Use-sfdisk-instead-of-parted-to-resize-root-p.patch

The partition being extended is in use and sfdisk can't reload such
partition table. Tell it to not even try, it will be done by partprobe
call below.
This is not yet complete, OpenQA reports also another issue:
open: No such file or directory while opening /dev/mapper/dmroot
Happens on Whonix only

Fix misleading error message on rootfs resize

---

network/update-proxy-configs

Starting from pacman v5.2.0 there is a problem with updating/installing
new packages:
$ pacman -Sy
...
debug: running command: ALL_PROXY=http://127.0.0.1:8082/ /usr/bin/curl -C - -f https://gluttony.sin.cvut.cz/arch/core/os/x86_64/core.db > /var/lib/pacman/sync/core.db.part
warning: running XferCommand: fork failed!
...
The problem is caused by change in pacman "run XferCommand via exec" [0].
Refs.:
- [0] https://git.archlinux.org/pacman.git/commit/?id=808a4f15ce82d2ed7eeb06de73d0f313620558ee
- [1] https://github.com/QubesOS/qubes-issues/issues/5443

archlinux: fix proxy setting in XferCommand

---

network/update-proxy-configs

This makes it easier to understand why this configuration is present.

Mention Update Proxy in configuration

---

qubes-rpc/qubes.StartApp

The workaround is no longer necessary, and it breaks when
the app name itself contains .desktop (such as org.telegram.desktop).
Fixes QubesOS/qubes-issues#5408.

StartApp: remove workaround for .desktop suffix

---

qubes-rpc/qubes.GetAppmenus

The script depends on XDG_DATA_DIRS environment variable
being set up correctly, which is not the case when it is
running under sudo. As a result, a post-install trigger
for apt could remove application entries from other sources
(Snap, Flatpak).
Fixes QubesOS/qubes-issues#5477.

GetAppmenus: ensure right app directories

---

misc/qubes-session-autostart

Fixes QubesOS/qubes-issues#5043.

qubes-session-autostart: handle error when reading a directory

---

debian/qubes-core-agent-nautilus.install
qubes-rpc/nautilus/Makefile
qubes-rpc/nautilus/qvm_nautilus_bookmark.sh
qubes-rpc/qubes.Filecopy
rpm_spec/core-agent.spec.in

A small script will add the QubesIncoming shortcut to Nautilus file pane
on the first use of qvm-copy to a given VM. The shortcut will not be recreated if
deleted.
fixes QubesOS/qubes-issues#2229

Added "QubesIncoming" shortcut to Nautilus

---

network/ip6tables-enabled
network/iptables

Packets detected as INVALID are ignored by NAT, so if they are not
dropped, packets with internal source IPs can leak to the outside
network.
See:
https://bugzilla.netfilter.org/show_bug.cgi?id=693
http://www.smythies.com/~doug/network/iptables_notes/
Fixes QubesOS/qubes-issues#5596.

firewall: drop INVALID state TCP packets

---

debian/qubes-core-agent-passwordless-root.postrm

The Package  includes an attempt to remove user from sudo group on removal, but the user is *not* a member of that group.
Remove reference in post-removal instructions.
Closes  QubesOS/qubes-issues#5469

Do not reference sudo group when removing Debian package

---

init/functions
init/setup-rwdev.sh

This reduces writes and improves speed on HDDs. On my machine, this change shrinks the size of a freshly created DispVM (at time of "disp9999 has started" notification) from ~97MiB to ~16MiB.
Additionally, this fixes is_dispvm(), which was previously unused but would report that a DispVM is an AppVM.

init: skip journal creation in DispVMs

---

debian/qubes-core-agent.install
package-managers/Makefile
package-managers/apt-conf-10no-cache

Closes QubesOS/qubes-issues#5266

Disable package caching in apt operations

---

qubes-rpc/qubes.GetAppmenus

Fixes QubesOS/qubes-issues#5296

qubes.GetAppmenus: skip unreadable .desktop files

---

app-menu/Makefile
app-menu/qubes-open-file-manager.desktop
rpm_spec/core-agent.spec.in

To be used by GUI tools to provide a convenient 'open file manager' shortcut.
references QubesOS/qubes-issues#5170

Added a qubes-open-file-manager.desktop file

---

qubes-rpc/qubes.GetAppmenus

.desktop files can have spaces around '=' symbols; previously
GetAppmenus discarded such files.
references QubesOS/qubes-issues#5692

fixed qubes.GetAppmenus ignoring some correct .desktop files

---

debian/changelog
debian/control

This is the only issue preventing focal build of core agent and in turn vm template construction.

Fix dependencies for Ubuntu 20.04 LTS (Focal Fossa)

---

app-menu/qubes-open-file-manager.desktop

Looks like desktop entries doesn`t allow environment variables in Exec string.
>qubes.StartApp+qubes-open-file-manager-dom0[1782]: gio: file:///home/user/$HOME: Error when getting information for file “/home/user/$HOME”: No such file or directory
switching to '.' resolve it.

Fix home path in qubes-open-file-manager.desktop

---

qubes-rpc/prepare-suspend

Needed and potentially sufficient for sys-gui-gpu suspend.
Part of: QubesOS/qubes-issues#2618

Skip IGD when unbinding device drivers on suspend

---

passwordless-root/polkit-1-qubes-allow-all.pkla
passwordless-root/qubes.sudoers

Without this restriction system users can start processes with root privileges:
```
$ sudo -u mail systemd-run --pipe -q id
uid=0(root) gid=0(root) groups=0(root)
```
This change restrict passwordless access to group qubes bringing it in line with `sudo` and `su`.
I also changed the sudoers file to allow group `qubes` rather than user `user`. This change is merely for consistency. Before `sudo` was restricted based on user and `su` based on group.

PolicyKit: only grant passwordless access to group qubes

---

package-managers/qubes-download-dom0-updates.sh

Resolves issue where the dom0 rpm database does not get used on
successive calls to qubes-dom0-update for debian updatevms.
Also resolves "cannot remove .rpmdbold.####" occurrences.
qubesos/qubes-issues#6124

Overwrite .rpmdb for debian updatevm

---

Makefile
boot/grub.qubes
debian/qubes-core-agent.install
init/setup-rwdev.sh
rpm_spec/core-agent.spec.in
vm-systemd/75-qubes-vm.preset
vm-systemd/dev-xvdc1-swap.service
vm-systemd/qubes-sysinit.sh
vm-systemd/systemd-fsck-root.service.d/30_qubes.conf

When the fsck is run in the target system, make sure it is started after
enabling swap. In recent Fedora versions, it can also run in initramfs - that
part will be handled in dracut module (linux-utils repository). Here just
ensure the root= parameter is properly set in grub (in case of in-VM kernel use).
Fixes QubesOS/qubes-issues#6174

Order swap before systemd-fsck-root.service

---

rpm_spec/core-agent.spec.in

Currently, `qubes.ShowInTerminal` doesn’t work in VMs based on minimal templates.

qubes.ShowInTerminal requires socat

---

qubes-rpc/qubes.GetAppmenus

Fixes https://github.com/QubesOS/qubes-issues/issues/6163
This PR replaces custom reloading of /etc/profile.d scripts with /etc/profile, which may load additional vars/functions that are needed by the scripts in /etc/profile.d

Replace custom script reloading with sourcing /etc/profile

---

qubes-rpc/qubes.ShowInTerminal

The socket path will be included in a shell command and then as a socat
argument, so only allow a small subset of known-safe characters.  In
practice, this has not been a problem because mktemp doesn’t include
these characters in its output.

Only allow known-safe characters in socket paths

---

config-overrides/sudoers.d_umask

The comment already mentions 022, which is presumably what was intended.

Use 022 instead of 002 as sudo umask

---

archlinux/PKGBUILD
package-managers/upgrades-installed-check
qubes-rpc/qubes.InstallUpdatesGUI

Partial fix QubesOS/qubes-issues#6239
The remaining part is
but as @DemiMarie reported «The Qubes updater uses SaltStack to update VMs, not qubes.InstallUpdatesGUI». But I don't know yet how Salt is working.
_For information_, below my change of qubes.InstallUpdatesGUI:
```
diff --git a/qubes-rpc/qubes.InstallUpdatesGUI b/qubes-rpc/qubes.InstallUpdatesGUI
index e01bace..952148b 100755
--- a/qubes-rpc/qubes.InstallUpdatesGUI
+++ b/qubes-rpc/qubes.InstallUpdatesGUI
@@ -20,4 +20,8 @@ fi
xterm -title update -e su -s /bin/sh -l -c "$update_cmd; echo Done.; test -f /var/run/qubes/this-is-templatevm && { echo Press Enter to shutdown the template, or Ctrl-C to just close this window; read x && poweroff; } ;"
-su -s /bin/sh -c 'service qubes-update-check start'
+if [ -e /etc/arch-release ]; then
+ …
```

Issue #6239

---

rpm_spec/core-agent.spec.in

Users who have their own SELinux policies should be able to keep QubesOS
from disabling SELinux.

Allow SELinux to stay enabled

---

vm-systemd/qubes-core-agent-linux.tmpfiles

It causes systemd to emit warnings.

Avoid deprecated /var/run directory

---

qubesagent/firewall.py

Fixes QubesOS/qubes-issues#6290 as a last resort in the event a domain part is too long (>64 chars) or empty (eg `host..name.com`).
Behavior is same as a DNS resolution failure: block all traffic.

Handle UnicodeError in firewall when resolving hostname

---

init/functions
package-managers/upgrades-installed-check
package-managers/upgrades-status-notify

The network-uplink-wait.sh script may be called before xen-netfront
module is even loaded (by udev). In that case, `get_qubes_managed_iface`
will fail to get the interface name and the wait will be skipped.
Fix this by loading xen-netfront module explicitly (do not try to
synchronize with udev, which is tricky not knowing the device
name).

network: fix waiting for VM network uplink

---

vm-systemd/qubes-early-vm-config.service

The unit on the Before= side of network-pre.target also has to pull it
in as a dependency:
https://www.freedesktop.org/software/systemd/man/systemd.special.html#network-pre.target
Fixes QubesOS/qubes-issues#5570

qubes-early-vm-config.service: Wants=network-pre.target

---

rpm_spec/core-agent.spec.in

qubes-core-agent-networking package brings in new systemd units, which
needs to be enabled. Standard %systemd_post macro handles it only on
initial installation, but not on update. The function that handle
updates is in %post of qubes-core-agent-systemd package. To avoid
duplication, simply enforce proper installation order, instead of
modifying %post of qubes-core-agent-networking package.
OrderWithRequires influences only ordering, but does not introduce
actual dependency, so it's still possible to not install
qubes-core-agent-networking package.
Fixes 0e0c229 "rpm: enable qubes-network-uplink.service on install"

rpm: order -systemd post script after -networking

---

package-managers/qubes-download-dom0-updates.sh

They are useless and can cause errors.

Avoid passing options to ‘dnf clean’

---

Makefile
debian/qubes-core-agent-network-manager.install
network/nm-31-randomize-mac.conf
rpm_spec/core-agent.spec.in

We do have NetworkManager new enough to handle this feature already.
Enable both scan MAC address randomization, and also connection mac
address randomization. The later do in a "stable" way - preserving the
same MAC _for a connection_, until reboot. This is a safe tradeoff
between full random, which breaks some captive portals. The stable MAC
is generated separate for each connection, so it also prevents
correlation of the same machine between different networks.
Do not enable it for wired connections, as those are less often used at
random untrusted localizations, but also more often it's desired to
get the same IP address each time (having random MAC would make it much
harder).
QubesOS/qubes-issues#938

network: enable MAC randomization for wifi connections by default

---

qubesagent/xdg.py

Should fix https://github.com/QubesOS/qubes-issues/issues/6346 
quit loop only when the original process is terminated.
The previous behavior was to quit the loop when any process is terminated

fix #6346: quit loop only when the original process is terminated

---

doc/vm-tools/qvm-open-in-dvm.rst

Intended behavior is for qvm-open-in-dvm to be able to handle URLs or filenames, but the man page made no reference of URLS. Updated the documentation to reflect that.

Add to man page that qvm-open-in-dvm can handle a URL -  Update qvm-open-in-dvm.rst

---

qubes-rpc/qvm-open-in-vm

should fix QubesOS/qubes-issues#6562.
The assumption that I made is that there is no case where we need to have a non-empty stdout when handling URL in qvm-open-in-vm.
(At least, tested if against my firefox issue, and it work as expected. But didn't ran more extensive tests)

fix #6562. qvm-open-in-vm: wait EOF when handling URL

---

qubes-rpc/thunar/uca_qubes.xml

They currently show up as warning icons instead

Fix Thunar icons

---

qubesagent/firewall.py
qubesagent/test_firewall.py

This can e.g. allow DNS applications to pin a FQDN to the IP
used during Qubes OS firewall setup.
Can help with QubesOS/qubes-issues#5225 and other related issues.

Export DNS information obtained during firewall setup to QubesDB

---

Makefile
debian/qubes-core-agent.install
rpm_spec/core-agent.spec.in
vm-systemd/systemd-logind.service.d/30_qubes.conf

Upon VM unpause the watchdog may otherwise trigger and restart the
service. Since a systemd-logind restart causes Xorg to restart,
qubes-gui-agent runs into issues, VM windows close down and disposable
VMs are shut down.
So for the sake of reliable unpausing it's better to just disable it.
Fixes QubesOS/qubes-issues#5988
Thanks again to @rustybird for the hint on where to put this.

systemd-logind: disable watchdog

---

app-menu/Makefile
app-menu/qvm-open-in-dvm.desktop
doc/vm-tools/qvm-open-in-dvm.rst
doc/vm-tools/qvm-open-in-vm.rst
rpm_spec/core-agent.spec.in

This is adding a "open in disposable VM" option to desktop environment.  For example, when using a file browser, right clicking then selecting "open with" would give opening in a disposable VM as a option.  file browsers are not the intended target as they already have this functionality built in, but this makes it a option for 
this allows things like: 
`xdg-settings set default-web-browser qvm-open-in-dvm.desktop`
to be done by the user.
This does not change any any of the system defaults and it does not get used automatically

Add a "open in disposable VM" to desktop environment

---

network/qubes-nmhook

This PR (at least partly) addresses https://github.com/QubesOS/qubes-issues/issues/5648 as currently, DNS resolution will not work for VPN connections configured via the `NetworkManager`, because `qubes-nmhook` is not executed for `vpn-up` events.

Also reload DNS on "vpn-up" event from NetworkManager

---

archlinux/PKGBUILD
vm-systemd/serial-getty@.service.d/30_qubes.conf

Nested logins don’t really work on Linux, and one often wants to login
as ‘user’, not as ‘root’.

Allow user to choose username for qube console login

---

debian/qubes-core-agent.links

Without these, anything using the GTK file dialong that has been set to
open files in a disposable qube crashes.  This prevents attaching files
to an email in Thunderbird, for example.
Fixes QubesOS/qubes-issues#7038.

Add missing symlinks to Debian qubes-core-agent

---

rpm_spec/core-agent.spec.in

This is especially needed since misc/Makefile expects VERSION variable
set in the main makefile. Otherwise marker-vm file is broken (lacks version
info).

rpm: build misc and qubes-rpc dirs via the main makefile

---

package-managers/upgrades-installed-check

set -e causes an early exit rather than correct behavior when checkupdates returns 2.
This PR makes it so that the script only prints true or false when exit codes are valid, and otherwise exits with the error code.
For context, I needed to fix this to pass qubes-dist-upgrade stage 1 normally.

fix upgrades-installed-check for archlinux

---

archlinux/PKGBUILD

The python v3.10 is finally out in the official arch repositories:
- https://archlinux.org/packages/core/x86_64/python/
The python dependecy should be updated. This change should be also backported to PKGBUILD for Qubes v4.0.
@lubellier, could you help me to test this change?
I have tested the change in my arch template and it seems that everything works as expected.
Thanks,
O.

qubes-vm-core: allow python<3.11 as a dependency

---

network/setup-ip
network/vif-qubes-nat.sh
network/vif-route-qubes

They cause all sorts of regressions, of which QubesOS/qubes-issues#7123
is just the most recent.  In the future, Qubes OS should switch to pure
layer-3 links between qubes, with no layer-2 addressing at all.  That is
for another day, however.
Fixes QubesOS/qubes-issues#7123 and possibly a few other issues.

Remove `ip neighbor` hacks

---

package-managers/Makefile

The packaging scripts attempt to install download.py and fail if it isn't present

Unbreak package build on Ubuntu builds

---

qubes-rpc/qubes.ShowInTerminal

It causes nasty problems when using vim, for example.
Fixes QubesOS/qubes-issues#7209.

qubes.ShowInTerminal: do not exit on Ctrl-O

---

Makefile
debian/qubes-core-agent.install
debian/qubes-core-agent.links
init/functions
rpm_spec/core-agent.spec.in
vm-systemd/qubes-random-seed.sh
vm-systemd/systemd-random-seed.service.d/30_qubes.conf

The random seed seems to (rarely) not get initialized.  This will ensure
that the random seed must be initialized for the system to successfully
boot.

Fail boot if random seed doesn't get initialized

---

archlinux/PKGBUILD
debian/control
network/setup-ip
network/vif-route-qubes
rpm_spec/core-agent.spec.in

The ifconfig command is obsolete on Linux.  Replace it with `ip` from
the iproute2 package.  This allows dropping the net-tools dependency
altogether.
Fixes QubesOS/qubes-issues#7142.

Replace net-tools with iproute2

---

vm-systemd/qubes-sysinit.sh

It is a security risk, slows qube boot, wastes memory and CPU, and is
not necessary.  Fixes QubesOS/qubes-issues#5179.
Reported-by: Patrick Schleizer <adrelanos@whonix.org>
@adrelanos I hope I got the Reported-by correct.

Disable CUPS by default

---

debian/qubes-core-agent.install
package-managers/Makefile
package-managers/apt-conf-41error-on-any

This uses the `APT::Update::Error-Mode` configuration option introduced
in Debian 11 to ensure that all errors in APT cause a non-zero exit
code.
Fixes QubesOS/qubes-issues#1107.
Reported-by: Patrick Schleizer <adrelanos@whonix.org>
Co-authored-by: Patrick Schleizer <adrelanos@whonix.org>

Make `apt-get update` exit codes reliable

---

archlinux/PKGBUILD
debian/control
network/setup-ip
rpm_spec/core-agent.spec.in
vm-init.d/qubes-firewall
vm-systemd/network-proxy-setup.sh

There is no reason to *not* have scatter-gather and checksum offload
turned on.

Turn on scatter-gather and checksum offload

---

Makefile
debian/qubes-core-agent-networking.install
qubes-rpc/qubes.WaitForSession
rpm_spec/core-agent.spec.in
vm-systemd/80-qubes-vif.link

Fix network renaming issue, and make VM startup more reliable.
Fixes QubesOS/qubes-issues#7284

Various fixes

---

network/vif-qubes-nat.sh
network/vif-route-qubes

This is consistent with proxy ARP; if one is enabled, the other should be as well.
The first commit improves error handling for IPv6 being disabled.  The second commit is the actual fix, and the third commit removes an unused variable.

Enable proxy NDP if IPv6 is enabled

---

network/setup-ip

See commit messages for details.
Fixes QubesOS/qubes-issues#7429

Workaround systemd's broken /etc/resolv.conf symlink

---

boot/grub.qubes

The 'tsc' clocksource is significantly faster than 'xen', and since
Qubes OS does not support VM migration, it is safe to use.
In synthetic benchmarks, it improves performance over tenfold, but
significant improvements in real world use cases is visible too.
Apply the change to in-VM kernel too.
Fixes QubesOS/qubes-issues#7404

Switch default clocksource to 'tsc'

---

qubesagent/firewall.py

Fixes https://github.com/QubesOS/qubes-issues/issues/7418
Tested 2 cases with `sys-firewall` running Debian bullseye (runuser in `/sbin/runuser`):
1. Added `qvm-firewall sys-vpn add --before 0 accept i-do-not-exist.example.com` and noticed the error notification from notify-send after `sudo systemctl restart qubes-firewall`.
2. Temporarily moved /sbin/runuser and confirmed that the exception is caught, notify-send notification does not appear but an error message `Failed to notify the user about: ...` is logged in `sys-firewall` log.

firewall log_error: handle all exceptions, allow runuser to be in /sbin

---

qubes-rpc/qvm-copy

qvm-copy has its own error reporting mechanism, which is where all
normal errors will go.

qvm-copy: Always filter escape characters in stderr

---

debian/qubes-core-agent-networking.install
network/Makefile
network/get-dns-from-resolved
network/qubes-setup-dnat-to-ns
rpm_spec/core-agent.spec.in

When a qube provides network to others, it needs to forward DNS traffic.
If /etc/resolv.conf points at local systemd-resolved, redirecting to it
won't work (and is not a good idea). Instead, forward such queries to
systemd-resolved's upstream servers.
Add a script to get the addresses using systemd-resolved's DBus API.
Fixes QubesOS/qubes-issues#7469

network: extract DNS servers IP from resolved service

---

Makefile
archlinux/PKGBUILD.install
debian/qubes-core-agent.install
debian/qubes-core-agent.postinst
rpm_spec/core-agent.spec.in
vm-systemd/75-qubes-vm.user-preset

We don't have pipewire plugin yet, and it conflicts with pulseaudio when
accessing physical audio cards (sys-audio case).
Fixes QubesOS/qubes-issues#7485
Related to QubesOS/qubes-issues#6358

Disable pipewire by default

---

vm-init.d/qubes-updates-proxy

732e9d02eeae18c3cfe3c10beceed1564f28c399 removed most of the network-based updates proxy, but it didn't change the SysV init scripts.

Rip out network-based update proxy remanents     

---

qubes-rpc/qvm-template-repo-query

If curl fails, but some data was downloaded already, retry from that point.
This should help with downloading on unstable network connection. The
implementation supports also switching to another mirror, but sadly
`dnf download --url` doesn't list them. That's a task for another time.
Reported at
https://forum.qubes-os.org/t/error-canonicalizing-file-payload-forged-in-qvm-template-gui/8391

qvm-template: resume failed downloads

---

network/setup-ip

Host scope means "only valid within this host", which is certainly not
correct for Xen virtual devices.  Link scope means "only valid in the
context of this link", which is correct.
Fixes: QubesOS/qubes-issues#7123.
Suggested-by: Ente <ducksource@duckpond.ch>

Use link scope for routes

---

qubes-rpc/prepare-suspend

There is no need to disable virtual (dummy) interfaces before suspend, it
matters only for physical ones. Especially, do not de-configure dummy eth1
used by Whonix, as there is nothing to turn it back on after resume.
QubesOS/qubes-issues#2044
QubesOS/qubes-issues#7404

prepare-suspend: do not disable virtual interfaces before suspend

---

qubes-rpc/nautilus/qvm_copy_nautilus.py
qubes-rpc/nautilus/qvm_dvm_nautilus.py
qubes-rpc/nautilus/qvm_move_nautilus.py

The get_file_items method of Nautilus.MenuProvider no longer take the window argument.
https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html
Fixes: QubesOS/qubes-issues#7916

qubes-rpc/nautilus: Add support for Nautilus API 4.0

---

qubes-rpc/nautilus/qvm_copy_nautilus.py
qubes-rpc/nautilus/qvm_dvm_nautilus.py
qubes-rpc/nautilus/qvm_move_nautilus.py

Using [GLib.spawn_async](https://lazka.github.io/pgi-docs/#GLib-2.0/functions.html#GLib.spawn_async) instead of subprocess.call or subprocess.Popen 
This prevents Nautilus from getting stuck while executing external commands. And no zombies.
As far as I've tried, Nautilus 43 on fedora-37 gets stuck without closing the context menu when calling external commands synchronously, so it should also help prevent that.
I tested with debian-10 and fedora-37 templates.

qubes-rpc/nautilus: Execute external commands asynchronously

---

debian/qubes-core-agent-dom0-updates.install
package-managers/Makefile
package-managers/dnf-plugin-downloadurl.py
qubes-rpc/qvm-template-repo-query
rpm_spec/core-agent.spec.in

If download from a selected mirror failed to start at all (missing file,
connection error etc), fallback to another mirror. This requires getting
all the mirror URLs from dnf, and the default dnf's 'download' plugin
does not expose this information. Use a modified plugin for this
purpose.

qvm-template: fallback to other mirrors

---

Makefile
archlinux/PKGBUILD
archlinux/PKGBUILD.install
debian/control
debian/qubes-core-agent.install
debian/qubes-core-agent.postinst
rpm_spec/core-agent.spec.in
vm-systemd/75-qubes-vm.user-preset

Move it together with related preset file that disables conflicting
pipewire.
That was the last user service drop-in file in this package, but leave
makefile rules in place in case some other will be added.
This is an alternative to #389

Move pulseaudio drop-in to pulseaudio-qubes package

---

selinux/qubes-qfile-unpacker.te

This broke due to an SELinux policy bug.

Fix restoring backup using DispVM

---

package-managers/qubes-download-dom0-updates.sh

When dom0 gets updated to newer Fedora, its rpmdb is in
/usr/lib/sysimage/rpm. Handle this case by checking for this directory
too - and check if that's really a directory, not a symlink to one.
QubesOS/qubes-issues#6982

Handle dom0 rpmdb in /usr/lib/sysimage/rpm too

---

network/qvm-connect-tcp

This also handles things like `qvm-connect-tcp --help`, which are otherwise met with a very unhelpful error message.

qvm-connect-tcp: print usage on invalid parameters

---

network/nm-31-randomize-mac.conf

Do not leak MAC address with each IPv6 connection when stateless
autoconfiguration is used.
The base MAC address is randomized for wifi anyway, but not for
ethernet.
QubesOS/qubes-issues#938

Enable IPv6 Privacy Extension by default

---

package-managers/qubes-download-dom0-updates.sh

This is especially relevant for older dom0 (in R4.1) - otherwise once
converted rpmdb won't be updated in subsequent calls. But add it to
newer systems too, in case similar logic will be necessary in the future
too.
Fixes: e7aed41 "Handle dom0 rpmdb in /usr/lib/sysimage/rpm too"
QubesOS/qubes-issues#6982

dom0-updates: force refreshing sqlite rpmdb if legacy one is newer

---

selinux/qubes-misc.te

The issue is fixed upstream already.
This reverts commit 0707922bb4a6aa5475289905ce37e8b0cbd8b635.

Revert "Workaround Fedora selinux preventing shutdown"

---

qubes-rpc/caja/qvm_copy_caja.py
qubes-rpc/caja/qvm_dvm_caja.py
qubes-rpc/caja/qvm_move_caja.py
qubes-rpc/kde/qvm-copy.desktop
qubes-rpc/kde/qvm-dvm.desktop
qubes-rpc/kde/qvm-move.desktop
qubes-rpc/nautilus/qvm_copy_nautilus.py
qubes-rpc/nautilus/qvm_dvm_nautilus.py
qubes-rpc/nautilus/qvm_move_nautilus.py
qubes-rpc/qopen-in-vm.c
qubes-rpc/thunar/qvm-actions.sh
qubes-rpc/thunar/uca_qubes.xml

Use qube instead of VM/AppVM, use the same wording everywhere and move from every-word-capitized to sentence capitalization
references QubesOS/qubes-issues#1015
references https://github.com/QubesOS/qubes-desktop-linux-manager/pull/150

Unify and improve wording on copy/move to other qube

---

archlinux/PKGBUILD.in

Update the python dependency for ArchLinux.
Related to https://github.com/QubesOS/qubes-issues/issues/8170

Update archlinux python version dependency to <3.12

---

selinux/qubes-misc.fc

This makes them unconfined while ensuring that programs they spawn have the correct (possibly confined) contexts.
Reported-by: Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>
Fixes: QubesOS/qubes-issues#8155

Xen hotplug scripts should be initrc_exec_t

---

app-menu/qubes-session-autostart
autostart-dropins/blueman.desktop
debian/qubes-core-agent.install
misc/Makefile
misc/qvm-service-wrapper
qubes-rpc/post-install.d/10-qubes-core-agent-features.sh
qubesagent/xdg.py
rpm_spec/core-agent.spec.in

It is useless without bluetooth controller (most qubes), and without loaded
rfkill module (also not useful in most cases) it crashes on start. See
linked issue for details.
It is still possible to enable it via 'blueman' qvm-service.
Fixes QubesOS/qubes-issues#8161

Disable blueman applet by default

---

debian/qubes-core-agent.postinst
rpm_spec/core-agent.spec.in

Do not fail package installation in chroot (like during template build
or in CI) - there, systemctl can't really communicate with real systemd,
but that isn't an error.

debian: fix postinst script in chroot

---

debian/qubes-core-agent.install
init/qubes-remount-lib-modules.sh
rpm_spec/core-agent.spec.in
vm-systemd/75-qubes-vm.preset
vm-systemd/qubes-remount-lib-modules.service

This unbreaks writing to /lib/modules with SELinux enforcing.
Reported-by: Marek Marczykowski-Górecki <marmarek@invisiblethingslab.com>
Fixes: QubesOS/qubes-issues#8144

Remount /lib/modules in early boot

---

rpm_spec/core-agent.spec.in
selinux/qubes-misc.fc

They should be `initrc_exec_t`, but due to an incorrect regular expression this did not happen.  `[!/]+` matches one or more `!` or `/` characters, whereas `[^/]+` matches one or more characters that are not `/`.

Label Xen hotplug scripts correctly

---

selinux/qubes-qfile-unpacker.fc
selinux/qubes-qfile-unpacker.te

This prevents it from writing outside of ~/QubesIncoming.  It would be preferable to prevent it from writing outside of the specific directory used for the given remote qube, but that would require qfile-unpacker to be SELinux-aware.

Jail qfile-unpacker in an SELinux sandbox

---

network/qubes-ipv4.nft
network/qubes-ipv6.nft

This unbreaks container networking, wireless hotspots, and much more.
Reported-by: Frédéric Pierret <frederic.pierret@qubes-os.org>
Fixes: QubesOS/qubes-issues#8222

Allow forwarding traffic that did not originate from netback

---

archlinux/PKGBUILD.install
debian/qubes-core-agent-caja.install
debian/qubes-core-agent-thunar.postinst
debian/qubes-core-agent-thunar.postrm
debian/qubes-core-agent.postinst
debian/qubes-core-agent.preinst
qubes-rpc/caja/Makefile
qubes-rpc/caja/qvm_caja_bookmark.sh
qubes-rpc/dvm2.h
rpm_spec/core-agent.spec.in

Qubes VMs can have any default user permitted by the operating system, provided that it can fit in qubesd.

Do not hard-code `user`

---

network/udev-qubes-network.rules
vm-systemd/qubes-network-uplink@.service

SYSTEMD_WANTS= does not conflict with existing systemd jobs.  Therefore, if a stop job is in progress for qubes-network-uplink@eth0.service, a new start job will not be queued after it.  The result is that qubes-network-uplink@eth0.service stays stopped and the qube has no network access.
Additionally, systemd assumes that udev change events are harmless, but the rule is written such that a change event would clear SYSTEMD_WANTS. This is incorrect.
Per [a comment by Lennart Poettering][1] it appears that SYSTEMD_WANTS+= is intended for persistent daemons, not short-running scripts. Furthermore, `man 7 udev` states:
> Running an event process for a long period of time may block all
> further events for this or a dependent device.
which implies that events for _other_ devices will continue …

Fix rapid network uplink disconnect and reconnect

---

selinux/qubes-qfile-unpacker.fc
selinux/qubes-qfile-unpacker.te

This requires using the special HOME_DIR keyword in the .fc file and ensuring that the appropriate labels are included in the relevant type_transition rule in the .te file.

Ensure correct labeling of ~/QubesIncoming

---

debian/qubes-core-agent.install
misc/Makefile
misc/xfce4-notifyd.xml
rpm_spec/core-agent.spec.in

Upstream decided to not use override-redirect windows for notifications
and use _MOTIF_WM_HINTS to mark those windows as borderless. The reason
was to not show the notifications over the screenlocker. In Qubes, we
have no intention of passing all possible window properties to the real
X server, but also the screenlocker issue doesn't apply as the
gui-daemon takes care to not show those above.
Thanks @rustybird for finding the solution.
Fixes QubesOS/qubes-issues#8181

(Re-)enable override-redirect windows in xfce4-notifyd

---

package-managers/dnf-plugin-downloadurl.py

pkg.repo._repo.getMirrors() returns only mirrors from metalink, if there
is none, the return is empty list. Fix this by falling back to
pkg.remote_location() that handles also baseurl.
Fixes QubesOS/qubes-issues#8299

qvm-template: fix handling repos with just baseurl set

---

vm-systemd/qubes-antispoof.service
vm-systemd/qubes-iptables.service
vm-systemd/qubes-network-uplink@.service

network-pre.target is intended to be ordered after any service that sets up a firewall and before any service that enables networking. Therefore, have network-pre.target require qubes-antispoof.service (unconditionally) and qubes-iptables.service (only if qubes-iptables.service is enabled).  qubes-network-uplink@.service now has Requires= and After= dependencies on network-pre.target, so it is ordered after both Qubes and third-party firewall rules.

Use network-pre.target to order firewall before network uplink

---

debian/qubes-core-agent.gsettings-override

Having an ibus tray icon from every (Debian bookworm) qube pollutes the
tray a lot. Disable it.
Fixes QubesOS/qubes-issues#8286

Hide ibus icon by default

---

archlinux/PKGBUILD.in
debian/control
network/qubes-iptables
rpm_spec/core-agent.spec.in

iptables is not used any more.
Fixes: QubesOS/qubes-issues#5301
Fixes: QubesOS/qubes-issues#8346

Drop requirement on iptables

---

network/setup-ip

This patch fixes network uplink failures on Fedora 37 and Debian 11 VMs with only one vCPU.  There is an underlying problem that causes the script to be run more than once, but this patch is a workaround until that bug can be found and fixed.
Fixes: QubesOS/qubes-issues#8305
Fixes: QubesOS/qubes-issues#8362

Do not fail if address already exists

---

package-managers/qubes-download-dom0-updates.sh

Fix checking if dom0's (bdb format) rpmdb is newer than converted one
(sqlite format in either /var/lib/rpm or /usr/lib/sysimage/rpm
directory).
The issue was that '-nt' consider existing file always newer than
non-existing one. This means, the logic selected to remove (supposedly)
old /var/lib/rpm/rpmdb.sqlite, instead of
/usr/lib/sysimage/rpm/rpmdb.sqlite when the former doesn't exist.
This fix is necessary for R4.1->R4.2 upgrade and needs to be backported
to release4.1 branch.
QubesOS/qubes-issues#7832

dom0-update: fix rpmdb migration logic

---

archlinux/PKGBUILD.install
debian/qubes-core-agent.install
debian/qubes-core-agent.postinst
debian/rules
misc/Makefile
misc/set-default-text-editor
rpm_spec/core-agent.spec.in

Debian does not define default application, so the choice is a bit
random (in practice - lexicographical). For text/plain, it hits
LibreOffice, which is very unfriendly for text/plain. Choose something
that is not libreoffice instead.
Fedora does define gedit as default editor, but xdg-open doesn't handle
mimeapps.list, it only looks for defaults.list file. Add a symlink to
fix this.
Fixes QubesOS/qubes-issues#8385

Set default text/plain editor to something not LibreOffice

---

init/functions
init/setup-rw.sh
network/network-manager-prepare-conf-dir

This is needed for disposable sys-net to work properly.  Without it /rw is not labeled correctly, causing SELinux to (correctly) block NetworkManager's writes to /rw/config/NM-system-connections.
Fixes: QubesOS/qubes-issues#8242

Set correct SELinux contexts on /rw

---

Makefile
debian/qubes-core-agent.install
rpm_spec/core-agent.spec.in
vm-systemd/user/evolution-addressbook-factory.service.d/30_qubes.conf
vm-systemd/user/evolution-calendar-factory.service.d/30_qubes.conf
vm-systemd/user/evolution-source-registry.service.d/30_qubes.conf
vm-systemd/user/evolution-user-prompter.service.d/30_qubes.conf
vm-systemd/user/tracker-extract-3.service.d/30_qubes.conf
vm-systemd/user/tracker-miner-fs-3.service.d/30_qubes.conf
vm-systemd/user/tracker-miner-fs-control-3.service.d/30_qubes.conf
vm-systemd/user/tracker-miner-rss-3.service.d/30_qubes.conf
vm-systemd/user/tracker-writeback-3.service.d/30_qubes.conf
vm-systemd/user/tracker-xdg-portal-3.service.d/30_qubes.conf

This allows services that are currently started in every non-minimal Fedora qube to be controlled via `qvm-service`.

Make services conditional

---

vm-systemd/qubes-sysinit.sh

Contrary to initial tests, disbling those do break some applications.
So, do not disable them by default in AppVMs.
But keep them disabled in system vms, as user applications are not
expected there.
QubesOS/qubes-issues#8372

Do not disable tracker and evolution-data-server in AppVMs

---

debian/control
qubes-rpc/qvm-template-repo-query
rpm_spec/core-agent.spec.in

qubes-core-agent-dom0-updates was missing a dependency on qubes-repo-templates, so the OpenPGP keys needed with repo_gpgcheck=1 weren't available to DNF.  Also add -y to the DNF command line so that it imports these keys without a prompt.
Fixes: QubesOS/qubes-issues#7414

Fix qubes.TemplateSearch with repo_gpgcheck=1

---

network/setup-ip

I found this tiny error when reading through the file. When trying to resolve the `/net-config/<mac address>` prefixed network settings from `qubesdb`, a missing slash garbles the paths.
That is, `"${prefix}ip"` would turn into something like `"/net-config/00:16:3e:5e:6c:00ip"` instead of the intended `"/net-config/00:16:3e:5e:6c:00/ip"`.

Fix tiny mistake in qubesdb path in `setup-ip`

---

Makefile
debian/qubes-core-agent.install
rpm_spec/core-agent.spec.in
vm-systemd/30_resolved-no-mdns-or-llmnr.conf

These protocols increase the attack surface of a VM that is exposed to attackers that are network-adjacent to that VM, such as VMs that this VM provides network to or that provide network to the VM.  LLMNR is deprecated in favor of mDNS, which is provided by Avahi in Fedora. Qubes OS already disables Avahi by default, so disabling LLMNR and mDNS
in systemd-resolved is unlikely to break any existing workflows.
Fixes: QubesOS/qubes-issues#8444

Disable multicast DNS and link-local multicast name resolution

---

debian/qubes-core-agent.install
qubes-rpc/Makefile
rpm_spec/core-agent.spec.in

Using this in the Qubes executor will allow using the Qubes executor with SELinux enforcing.

Provide a alternate qfile-unpacker that is not SELinux-confined

---

network/setup-ip

Fix the case when qube provides IPv6 to others (for example via VPN), but
isn't itself connected to IPv6-providing qube. In this case, it will
have an IPv6 address but not IPv6 gateway. Do not fail in this case.

Fix partial IPv6 setup

---

network/qubes-ipv6.nft

The rule to jump to custom-forward chain is present for ipv4:
https://github.com/QubesOS/qubes-core-agent-linux/blob/main/network/qubes-ipv4.nft#L24
But is missing for ipv6 so add it.

Add missing nft rule for ipv6 that is present for ipv4

---

qubesagent/xdg.py

Recent Fedora broke firefox.desktop, by setting DBusActivatable=true,
while having invalid dbus name.
Fallback to a classic launch if loading dbus object fails.
Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2242454
Fixes QubesOS/qubes-issues#8571
Replaces https://github.com/QubesOS/qubes-core-agent-linux/pull/463

Workaround broken desktop files

---

qubes-rpc/gui-fatal.c
qubes-rpc/qfile-unpacker.c

qfile-unpacker is setuid root so that it can call chroot().  Right now, it will happily change its filesystem UID to a value that is supplied on the command line, then chroot to a directory supplied on the command line, and finally create new files, directories, and symbolic links of the caller's choice.  This is enough to get root; a simple method is to drop a .conf file under /rw/bind-dirs (creating it if it does not exist) and wait for VM reboot.  The file will then be sourced as a shell script with root privileges.
Additionally, setuid() failing results in zenity or kdialog being run as root, which is not safe.  Neither zenity nor kdialog is safe when being run with privileges, and it is easy to make them execute arbitrary code by abusing GTK or Qt's environment variables. …

qfile-unpacker should not be an easy root hole

---

qubes-rpc/qvm-open-in-vm

If a VM is set to use a disposable VM to handle URLs and is also its also default disposable VM template, attempting to open a URL in that VM will cause the newly created disposable VM to create yet another disposable VM and so on.  This is effectively a fork bomb, and will continue to create disposable VMs until a resource (usually memory) is exhausted.
To prevent this from happening, check if the VM was spawned via qubes.OpenURL or qubes.OpenInVM, and if the target of a call to qvm-open-in-vm is a disposable VM.  If both hold, prompt the user before creating the disposable VM.  If prompting is not possible, fail.
Tested with a modified Fedora template.
Fixes: QubesOS/qubes-issues#7406

Detect and terminate infinite qrexec launch chains

---

init/setup-rw.sh
vm-systemd/misc-post.sh

Fixes https://github.com/QubesOS/qubes-issues/issues/8690

Parse rc.local.d directory on boot

---

qubes-rpc/gui-fatal.c
qubes-rpc/qvm-copy-to-vm.gnome

Fixes QubesOS/qubes-issues#8723
Fixes QubesOS/qubes-issues#8738

Filecopy GUI error message and kdialog progress bar fixes

---

debian/qubes-core-agent.install
misc/Makefile
misc/displays.xml
rpm_spec/core-agent.spec.in

Default Xfce setting is to prompt what to do when new display is
connected. It makes sense in dom0 (or GUI domain), but not really in
every VM. Disable it by default. When setting up GUI domain, it will
need to be re-enabled manually (or possibly via salt).
Fixes QubesOS/qubes-issues#8756

Do not show "Displays" prompt in every VM when new display is connected

---

config-overrides/Makefile
config-overrides/portals.conf
debian/qubes-core-agent.install
rpm_spec/core-agent.spec.in

Sandboxed applications use this to store secrets.  Without it, Element cannot access its secrets and resets itself, causing user data to be lost.  The version of xdg-desktop-portal in Fedora 38 and below would use any portal implementation it could find, but the version in Fedora 39 requires that portal implementations be specified in a config file. Provide that config file.
Fixes: QubesOS/qubes-issues#8839

Ensure XDG secrets portal is available

---

qubes-rpc/qvm-copy

In R4.2, these will be rejected on the receiving side with a confusing error.  Furthermore, the previous behavior (copying all files directly into `~/QubesIncoming/VMNAME`) wasn't intuitive either.  Just error out early with a more useful message.
Fixes: QubesOS/qubes-issues#8927

Refuse to copy "." or ".."

---

rpm_spec/core-agent.spec.in

Sandboxed applications use a secrets portal implementation to store secrets.  Without it, Element cannot access its secrets and resets itself, causing user data to be lost.  However, there is no guarantee that a specific keyring implementation is currently used or even present, which would allow QubesOS/qubes-issues#8839 to recur.
To fix this, ensure that gnome-keyring is _always_ present by making it a hard dependency if xdg-desktop-portal is present.  This does _not_ enforce that it is always used, as there is no way to do that without choosing _all_ portal implementations.  However, it is the best way to ensure that the user does not lose data when they switch between TemplateVMs.

Ensure gnome-keyring always available

---

qubes-rpc/vm-file-editor.c

Prevents easy escalation to the "qubes" group via a symlink attack.

Use `O_NOFOLLOW` for the log file

---

qubes-rpc/qubes.UpdatesProxy

Recent change in socat made it prefer ::1 address for localhost. This
breaks updates proxy, because it allowed only 127.0.0.1. Force the IPv4
address. An alternative could be allowing IPv6 address in the proxy
instead, but since IPv6 can be disabled (Whonix does it), it would mean
having different paths depending on IP settings, which could be
confusing at times.
Fixes QubesOS/qubes-issues#9025

Force using 127.0.0.1 when connecting to updates proxy

---

archlinux/PKGBUILD-qubes-repo-4.2.conf
archlinux/PKGBUILD.in

The actual repositories are installed via the meta-packages git repository.

Remove Arch repository stub

---

archlinux/PKGBUILD.in

ArchLinux switched to python-3.12, this PR fixes the https://github.com/QubesOS/qubes-issues/issues/9171 issue for qubes-core-agent-linux

Update archlinux python version dependency to <3.13

---

qubes-rpc/prepare-suspend

Detaching devices from their drivers is not needed with S0ix, in fact,
it's harmful then.
QubesOS/qubes-issues#6411

suspend: skip S3 related workarounds when using S0ix

---

debian/control
qubesagent/firewall.py
rpm_spec/core-agent.spec.in

It was relevant when qubes-firewall was started from SysV init script,
but it isn't the case anymore. Most of its features were disabled
anyway, and redirecting stdin/out/err is handled by systemd anyway.
This is the last usage of the library which isn't available in
Archlinux, and as such qubes-firewall service was broken there. Not
using this library should fix the issue.
Fixes QubesOS/qubes-issues#9238

Do not use python-daemon library

---

archlinux/PKGBUILD.in
archlinux/PKGBUILD.qubes-post-upgrade.hook

Resetting `updates-available` feature of Archlinux template after successful upgrades
Reference to issue: Fixes QubesOS/qubes-issues#9233

pacman hook to notify dom0 about successful upgrade

---

package-managers/qubes-download-dom0-updates.sh

When downloading updates for dom0, DNF's stdin is not connected to any terminal, so it makes no sense for DNF to ever prompt for interactive confirmation.  By default, DNF would prompt for confirmation before importing a metadata signing key, causing breakage.
This change fixes `qubes-dom0-update --check-only` using sys-whonix as UpdateVM.
Fixes: QubesOS/qubes-issues#9212

Always pass -y to DNF when downloading dom0 updates

---

qubes-rpc/tar2qfile.c

This fixes a -Werror=unused-but-set-variable failure.

Fix tar2qfile build with clang

---

qubes-rpc/post-install.d/10-qubes-core-agent-features.sh

Very useful to apply configuration based on the base distribution that the OS was created upon, instead of adding an extensive list of supported distributions of Debian.

Add os-release ID_LIKE to features

---

debian/control
debian/qubes-core-agent.install
qubes-rpc/Makefile
qubes-rpc/qfile-unpacker.c
qubes-rpc/qubes-fs-tree-check.c
qubes-rpc/qubes.Filecopy
qubes-rpc/qvm-copy
rpm_spec/core-agent.spec.in

This uses QREXEC_SERVICE_FULL_NAME to detect what the service was invoked as.  Non-empty arguments are reserved for future use.
This requires QubesOS/qubes-linux-utils#113.
Part of QubesOS/qubes-issues#8332

Allow unsafe characters if invoked as qubes.UnsafeFileCopy

---

network/qubes-setup-dnat-to-ns

Fixes https://github.com/QubesOS/qubes-issues/issues/9011
Details in Github comments and forum link

Fixing issue 9011: DNS leakage when only one DNS server is set

---

qubes-rpc/qfile-unpacker.c
qubes-rpc/qubes-fs-tree-check.c
qubes-rpc/qubes.Filecopy
qubes-rpc/qvm-copy

As pointed out by Andrew David Wong the latter name is unnecessarily alarming.  No backwards compatibility is provided because users should not need to remember to blocklist two different strings in their qrexec policies.  Denying "+allow-all-names" should be sufficient.
Reported-by: Andrew David Wong <adw@qubes-os.org>
Fixes: QubesOS/qubes-issues#8332 (for real this time)

Use allow-all-names instead of allow-unsafe-characters

---

qubes-rpc/qfile-agent.c
qubes-rpc/qvm-copy

qfile-agent: fix CLI progress display unit mismatch

---

boot/dracut-qubes.conf

This change reduces intramfs size to about 17MB.
Fixes QubesOS/qubes-issues#8540

Limit initramfs size to fix booting with limited memory size

---

network/setup-ip

Debian recently [1] removed the symlink in /sbin which breaks our setup-ip script.
Instead of hardcoding the new path, rely on normal $PATH resolution. Saving a few file existence checks isn't worth such breakage, I think (or if that really matters here, shell is the wrong tool in the first place).
[1]: https://salsa.debian.org/kernel-team/iproute2/-/commit/c4bb148dd4ed0601ca32ee8a458007d0c348d6c3
---
Assuming you agree with my reasoning above, one could argue to apply this change to all invocations of programs normally in the $PATH. Given that usage was already inconsistent I for now kept the change minimal instead.
The fix (this version or an update to /bin/ip) should be backported to 4.2.

 setup-ip: Invoke 'ip' via $PATH 

---

package-managers/qubes-download-dom0-updates.sh

Message for --check-only is moved to qubes-dom0-update 
main fix: https://github.com/QubesOS/qubes-core-admin-linux/pull/162
original issue: https://github.com/QubesOS/qubes-issues/issues/6126

Remove redundant qubes-dom0-update message

---

qubes-rpc/qvm-open-in-vm

fixes: https://github.com/QubesOS/qubes-issues/issues/9360

Accept only files for qvm-open-in-(d)vm

---

archlinux/PKGBUILD.in
archlinux/PKGBUILD.qubes-secure-path.sudo

fixes: https://github.com/QubesOS/qubes-issues/issues/9395

Patch /etc/sudoers on Archlinux

---

package-managers/qubes-download-dom0-updates.sh

dnf5 does not print "--downloadonly" help with -h by default
For https://github.com/QubesOS/qubes-issues/issues/9244

Support dnf5 for qubes-download-dom0-update.sh

---

package-managers/Makefile
package-managers/qubes-post-update.actions
qubes-rpc/qvm-template-repo-query
rpm_spec/core-agent.spec.in

DNF4 plugin we used to have for this doesn't work in Fedora 41 anymore. Use libdnf5-plugin-actions in DNF5.
QubesOS/qubes-issues#9244

Configure DNF5 to execute post-update actions

---

qubes-rpc/qvm-template-repo-query

related: https://github.com/QubesOS/qubes-core-admin-client/pull/308

Fix DNF5 repoquery

---

qubes-rpc/qvm-copy-to-vm.gnome

Fixes QubesOS/qubes-issues#9506

Support relaxed filenames in GUI filecopy too

---

vm-systemd/qubes-early-vm-config.sh

This allows to run arbitrary commands early in initialization, which is useful for things like replacing Qubes GUI packages in a specific VM.

Add support for /rw/config/rc.local-early to run commands as early as possible

---

boot/dracut-qubes.conf

Initramfs at 22MB is small enough to start in PVH mode, but too big to
start in HVM mode. Exclude tpm2-tss dracut module to save another 5MB,
which makes it work in HVM mode too.
QubesOS/qubes-issues#8540
QubesOS/qubes-issues#5212

Limit initramfs size in Fedora HVM even more

---

network/qubes-nmhook
network/qubes-setup-dnat-to-ns
network/setup-ip

NetworkManager will call the hook when anything about the connection
changes. In some cases (like multiple connections) this can be quite
often and restarting tinyproxy each time will eventually trigger restart
rate limit and keep the service down. But even if not hitting this
limit, restart interrupts any download in progress.
Add a check if DNS addresses actually changed since the las hook call,
and restart the service only when necessary.
As a side effect, this will also avoid restarting the service on DHCP
lease renew.
Fixes QubesOS/qubes-issues#9110

network: do not restart tinyproxy if DNS hasn't changed

---

debian/qubes-core-agent.install
misc/20-qubes-core.conf
misc/90-qubes-core.conf
misc/Makefile
rpm_spec/core-agent.spec.in

When VM is started with memory hotplug, the initial memory size is quite
small. It is used for calculating default threads limit, and that in
turns is used to calculate default process count limit per user. For a
VM started with 400MB (the default) both limits are too low for some
threads/processes-heavy applications like Firefox.
Adjust the limits to a static higher value, based on defaults when
memory hotplug is disabled (and rounded to a nice number).
Fixes QubesOS/qubes-issues#8960

Adjust default process/threads limit

---

qubes-rpc/qfile-agent.c
qubes-rpc/qvm-copy

`--` was stripped from the arguments before being passed to qfile-agent, so `qvm-copy -- --ignore-symlinks` would ignore symlinks instead of copying a file named `--ignore-symlinks`.  To fix this problem, always pass `--` to qfile-agent, preceeded by `--ignore-symlinks` if necessary.  This requires qfile-agent to honor `--` as indicating end of options, so patch it to do that.

qvm-copy: support `--ignore-symlinks` and honor `--`

---

debian/control

In bookworm, `policykit-1` is now a “transitional package”.
For example, see [Debian Changelog for network-manager](https://metadata.ftp-master.debian.org/changelogs//main/n/network-manager/network-manager_1.42.4-1_changelog):
1.40.6-1
* Depend on polkitd in preference to policykit-1.
The latter is a deprecated, transitional package, that also pulls in
pkexec, which network-manager doesn't need. Keep policykit-1 as an
alternative dependency to make backports easier.

debian: use polkitd instead of policykit-1

---

package-managers/Makefile
package-managers/dnf-harden.conf
rpm_spec/core-agent.spec.in

Not tested yet but hopefully works.

Harden DNF config in RPM post-install script

---

qubes-rpc/qubes-fs-tree-check.c

When processing directories, `process_dirent()` detected filenames that are unsafe for display and set `bad` to true, but `bad` was not used to determine the return value of `process_dirent()`.  Instead, the function tail-called `simple_fs_walk()`.  Therefore, directories with unsafe filenames were not detected.  This caused `qubes.Filecopy` to be used instead of `qubes.Filecopy+allow-all-names`.  `qubes.Filecopy` (correctly) rejects the directory.
Fix the bug by ensuring that if `bad` is set to true, `process_dirent()` returns true even if the function recurses into `simple_fs_walk()`.  This will cause `qubes.Filecopy+allow-all-names` to be used, which will accept the directory and allow the copy to succeed.
Fixes: QubesOS/qubes-issues#9567

qubes-fs-tree-check: Detect if a directory is unsafe for display

---

vm-systemd/tmp.mount.d/30_qubes.conf

The Qubes config for systemd /tmp mount options overrides the size of /tmp due to memory ballooning. However, it only copies some of the other options. This patch syncs with Fedora by also adding the options nosuid,nodev,nr_inodes=1m. Setting nosuid and nodev should have minor security benefits.
Increasing nr_inodes is important because otherwise the default is nr_inodes=44492, which is too few inodes for software like "opam" which uses /tmp as a staging directory.

Sync other systemd /tmp mount options with Fedora

---

archlinux/PKGBUILD.in
boot/Makefile
boot/dracut-qubes.conf
debian/qubes-core-agent.install
debian/rules
rpm_spec/core-agent.spec.in

Add dracut config to the Debian package too

---

.gitignore

No functional change intended.  This will help developers realize when there is a file in their working tree that should not be there.

Add missing .gitignore entries

---

archlinux/PKGBUILD.in

Needed to work with Python 3.13 on Arch.
Fixes: QubesOS/qubes-issues#9665

Bump Python version on Arch

---

app-menu/qubes-run-terminal

Fedora 41 defaults to using ptyxis as its terminal instead of gnome-terminal. It also works correctly in dispVMs without needing any special --wait handling.

Support ptyxis in qubes-run-terminal

---

qubes-rpc/qvm-copy

Previously, `qvm-copy` had a couple of issues with symlinks:
1. A trailing slash on the source could cause errors:
````
$ qvm-copy-to-vm untrusted dir/
qubes-fs-tree-check: Refusing to copy unsafe symbolic link "dir//my-symlink"
````
but `qvm-copy-to-vm untrusted dir` worked fine.
2. `qvm-copy --ignore-symlinks` could still throw `qubes-fs-tree-check: Refusing to copy unsafe symbolic link` . If we are ignoring symlinks, `qubes-fs-tree-check` should not check for them.
Running `qubes-fs-tree-check --ignore-symlinks --allow-symlinks` does not seem to cause an issue.

Fix qvm-copy behavior with symlinks

---

archlinux/PKGBUILD.install
vm-systemd/qubes-early-vm-config.sh

fixes: https://github.com/QubesOS/qubes-issues/issues/9710

Remove `hostname` dependency for Archlinux

---

archlinux/PKGBUILD.in
package-managers/qubes-download-dom0-updates.sh
qubes-rpc/post-install.d/10-qubes-core-agent-features.sh
vm-systemd/75-qubes-vm.preset

Add qubes-vm-dom0-updates subpackage, similar to other distributions.

archlinux: package tools for fetching dom0 updates

---

rpm_spec/core-agent.spec.in

The documentation says to install qubes-core-agent-network-manager, but the system can just do it for the user by pulling it in via an RPM rich dependency.
Fixes: QubesOS/qubes-issues#9664

Pull in qubes-core-agent-network-manager when installing NetworkManager

---

Makefile
debian/qubes-core-agent-networking.install
debian/qubes-core-agent.install
network/82-qubes-minimal-sys-net.conf.optional
qubes-rpc/post-install.d/10-qubes-core-agent-features.sh
qubes-rpc/prepare-suspend
qubes-rpc/qubes-suspend-module-blacklist
rpm_spec/core-agent.spec.in
vm-systemd/75-qubes-vm.preset
vm-systemd/abrtd.service.d/30_qubes.conf
vm-systemd/bluetooth.service.d/30_qubes.conf
vm-systemd/polkit.service.d/30_qubes.conf
vm-systemd/qubes-sysctl-minimal-sys-net.service
vm-systemd/user/at-spi-dbus-bus.service.d/30_qubes.conf
vm-systemd/user/gvfs-daemon.service.d/30_qubes.conf
vm-systemd/user/pipewire.service.d/40_minimal.conf
vm-systemd/user/wireplumber.service.d/30_qubes.conf

Some unnecessary services are running on sys-net and sys-usb which consumes RAM for nothing. SystemD dropins are added to automatically disable identified unecessary services by enabling minimal-netvm or minimal-usbvm  service on the sys-vms with qvm-service.

SystemD dropins for minimal sys-net and sys-usb

---

Makefile
debian/qubes-core-agent.install
rpm_spec/core-agent.spec.in
vm-systemd/systemd-nsresourced.service.d/30_qubes.conf
vm-systemd/systemd-nsresourced.socket.d/30_qubes.conf
vm-systemd/systemd-userdbd.service.d/30_qubes.conf
vm-systemd/systemd-userdbd.socket.d/30_qubes.conf

This disables two more services for minimal sys-net and minimal sys-usb (see https://github.com/QubesOS/qubes-core-agent-linux/pull/540)  :
* ``systemd-nsresourced.service`` and its socket ``systemd-nsresourced.socket``
* ``systemd-userdbd.service`` and its socket ``systemd-userdbd.socket``

Disable systemd-nsresourced and systemd-userdbd for minimal sys-net and minimal sys-usb

---

Makefile
debian/qubes-core-agent.install
filesystem/fstab
init/functions
qubes-rpc/prepare-suspend
qubesagent/firewall.py
rpm_spec/core-agent.spec.in
vm-systemd/75-qubes-vm.preset
vm-systemd/NetworkManager.service.d/30_qubes.conf
vm-systemd/bind-dirs.sh
vm-systemd/home.mount
vm-systemd/misc-post.sh
vm-systemd/mount-dirs.sh
vm-systemd/qubes-bind-dirs.service
vm-systemd/qubes-misc-post.service
vm-systemd/qubes-mount-dirs.service
vm-systemd/usr-local.mount

This PR adds a new feature ``custom-persist`` described in https://github.com/QubesOS/qubes-issues/issues/1006

New custom-persist feature

---

qubesagent/firewall.py
qubesagent/test_firewall.py

Long hostnames result in qubesdb paths that exceed the current 64 character limit.  Instead of crashing the firewall daemon, log the error and continue without adding the hostname to the DNS records.
This is a workaround, not a fix, for https://github.com/QubesOS/qubes-issues/issues/9084.  The fix requires either longer path support in qubesdb or using a different schema so that keys will not exceed the qubesdb path length limit.

Agent firewall long hostname crash

---

rpm_spec/core-agent.spec.in

New template updater (core-admin-linux vmupdate) uses tar for extracting update agent files.
But currently tar is not dependency of Qubes core components, so people maybe remove it mistakenly.
Adding tar to core-agent dependencies will reduces such risks.

qubes-core-agent: add tar to dependencies

---

rpm_spec/core-agent.spec.in

On Fedora 42, `script` executable is moved to `util-linux-script` package. It is required for `qubes-download-dom0-update.sh` to work.

Assure `script` is installed for dom0 update

---

network/vif-route-qubes

When 'vif-route-qubes offline' is called, the interface (usually)
doesn't exist anymore. In that case, commands are called with
'do_without_error', but while it doesn't fail the script, it still logs
misleading error message.
Avoid calling 'ip' on non-existing interface to remove its
address/route, as those are removed by the kernel implicitly anyway.
But still call them on online action (if interface doesn't exist at this
point, it will fail, and that's intentional to get proper error
message), or when the interface still exist at the time the script is
called (in which case, it may still race against disappearing the
interface, but then there is 'do_without_error' prefix as the
last resort). This way, it avoids confusing error in the common case,
but still ensure things are cleaned up …

Avoid de-configuring non-existing interface

---

autostart-dropins/pasystray.desktop
autostart-dropins/volumeicon.desktop

fixes: https://github.com/QubesOS/qubes-issues/issues/9158

Launch `volumeicon` and `pasystray` only for audiovm

---

rpm_spec/core-agent.spec.in

It's required for the qubes-vm-update tool to report progress of the
update.
QubesOS/qubes-issues#9244
Related to https://github.com/QubesOS/qubes-core-admin-linux/pull/187

rpm: require python3-libdnf5 on F41+

---

qubes-rpc/prepare-suspend

Intel wifi driver wants to allocate large contiguous memory blocks
(for example with Intel BE200 it's 128k). Try to force some memory
(possibly pushing some apps into swap) and then force memory compaction
- just before loading wifi drivers back (depending on device, module
either gets loaded, or just bound to the device).
Do this by using dd to allocate 512MB of memory. The amount is large
enough to force swapping, but it's still significantly below the swap
size (1GB) so it doesn't trigger OOM.
Fixes QubesOS/qubes-issues#9869

Free some memory on resume before re-loading modules

---

package-managers/upgrades-installed-check

The 'apt_get_update_output' variable is unused, so avoid complexity with
saving apt-get update output and printing it at the same time. This
fixes checking updates on Debian, as 'tee /proc/self/fd/2' fails when
the script is called from systemd service (via systemd timer).
Fixes QubesOS/qubes-issues#9895

Simplify logging apt-get update output

---

qubes-rpc/qvm-template-repo-query

This PR adds a wrapper in the payload sent for qubes.TemplateSearch and qubes.TemplateDownload RPC calls. This wrapper allows files to be sent to the Proxy VM that would be used by DNF .
To prevent conflict and permission issues, the files are not written in ``/etc/qubes/repo-templates/`` but in the temporary directory where the transmitted repository file is stored. Then, this repository file is patched in order to modify the path of the transmitted files.
https://github.com/QubesOS/qubes-issues/issues/9850

SSL auth and user GPG key support for user templates repos

---

archlinux/PKGBUILD.in
archlinux/PKGBUILD.qubes-post-upgrade.hook
package-managers/qubes-download-dom0-updates.sh
qubes-rpc/qvm-template-repo-query

archlinux: update dnf dependency

---

archlinux/PKGBUILD.in
archlinux/PKGBUILD.install

The custom persist feature relies on /home etc not being in /etc/fstab anymore.
See commit messages for details.
Fixes QubesOS/qubes-issues#9975

archlinux: Sync /etc/fstab with other distros

---

debian/qubes-core-agent.install
qubes-rpc/Makefile
qubes-rpc/qubes.WaitForRunningSystem
qubes-rpc/qubes.WaitForSession
rpm_spec/core-agent.spec.in

The 'gui' feature is not passed via QubesDB to the qube, if it was, only one service would be necessary.
For: https://github.com/QubesOS/qubes-issues/issues/1512
---
This makes the handler for `domain-start` simpler, besides not having to sleep if there is no GUI for a qube.

Wait for session only if necessary

---

Makefile
debian/control
debian/qubes-core-agent.install
rpm_spec/core-agent.spec.in
vm-systemd/75-qubes-vm.preset
vm-systemd/firewalld.service.d/30_qubes.conf

Retrying #580 :crossed_fingers: 
Currently, qubes-core-agent does not allow installation alongside firewalld. They seem to get along as fine as one would expect when allowed, though. Users should be allowed to use it if they want.
firewalld will not run even if the default systemd service is enabled: The service is actually enabled by presence of `/var/run/qubes-service/firewalld`.

 qubes-core-agent: remove conflict with firewalld

---

debian/qubes-core-agent.install
qubes-rpc/Makefile
qubes-rpc/qubes.VMRootExec
qubes-rpc/qubes.VMRootExec.config
qubes-rpc/qubes.VMRootShell.config
rpm_spec/core-agent.spec.in

Don't require setting user=root in each policy line for them
Fixes QubesOS/qubes-issues#9939

Use rpc-config for running qubes.VMRoot* services as root

---

qubes-rpc/qubes.WaitForSession

Generally we require dom0 to be updated before VM, so that qubesdb key
should always be there. But since handling the opposite case here is
easy, lets do that anyway.

Assume GUI is enabled if dom0 didn't provide that info

---

archlinux/PKGBUILD.in
debian/control

Make the archlinux and debian specs more maintainable by consistently sorting dependency lists alphabetically.
Includes #584

arch, debian: Sort dependencies

---

archlinux/PKGBUILD.in
qubes-rpc/nautilus/Makefile

Refactor archlinux package by breaking out `qubes-vm-nautilus` from `qubes-vm-core`.
This matches existing Debian and Fedora packaging.
- Blocking https://github.com/QubesOS/qubes-app-linux-pdf-converter/pull/34
- Same for caja and thunar: #589
- Includes #584 , #585 
---
The same could also be done for `-thunar` and `-caja`. With a tentative approval here I could address those as well, in this PR or separately.

arch: break out qubes-vm-nautilus from qubes-vm-core

---

archlinux/PKGBUILD.in
qubes-rpc/nautilus/Makefile

Break out `qubes-vm-caja` and `qubes-vm-thunar` from `qubes-vm-core` Arch package to match structure of Debian and Fedora packaging.
- Follow-up to #586 
- Blocking #590

arch: break out qubes-vm-caja, qubes-vm-thunar packages

---

network/qubes-setup-dnat-to-ns
vm-systemd/network-proxy-setup.sh

Two minor non-functional changes:
- remove unused `List` typing import
- Use `-n` instead of x-hack for checking for empty var in shell script
- Broken out from #592

network lint fixes

---

network/qubes-setup-dnat-to-ns

- I guess the existing memoization of `dns_` is for efficiency reasons? This uses the same pattern for the other `ip_address` instance in the string `vm_nameserver`. If nothing else it makes it more consistent.
- Use `itertools.cycle` instead of list-doubling to match up `zip` side lengths.
- Broken out from #592

install_firewall_rules: minor performance improvement

---

network/setup-ip
vm-systemd/network-proxy-setup.sh

The file `/var/run/qubes/qubes-ns` is not used since the transition to nftables (https://github.com/QubesOS/qubes-core-agent-linux/pull/407/files#diff-1e7c156682261fecd8a773620728327528f3be00468837709d7ffeb8073cc602L17).
Remove it and the associated now redundant `qubesdb-read` calls.
`qubes-ns` is also no longer used in qubes-whonix: https://github.com/Whonix/qubes-whonix/commit/451b784c6db5316289e16ac18fd496851f4c3a92

network: remove redundant qubesdb-read calls and /run/qubes/qubes-ns

---

archlinux/PKGBUILD.in
network/qubes-setup-dnat-to-ns

While package names match between Debian and Fedora (`qubes-core-agent{,-*}`), Arch packaging has its own naming (`qubes-vm-*`). This means that salt formulas that can otherwise be used seamlessly cross-dists need to be customized for Arch targets.
This adds `provides` directives for Arch packages so they can be installed by referring to their Debian/Fedora names.
- `qubes-core-agent` -> `qubes-vm-core`
- `qubes-core-agent-networking` -> `qubes-vm-networking`
- `qubes-core-agent-nautilus` -> `qubes-vm-nautilus`
- `qubes-core-agent-caja` -> `qubes-vm-caja`
- `qubes-core-agent-thunar` -> `qubes-vm-thunar`
- `qubes-core-agent-dom0-updates` -> `qubes-vm-dom0-updates`
- `qubes-core-agent-passwordless-root` -> `qubes-vm-passwordless-root`
`qubes-vm-keyring` unmapped.
Follow-up to #589

arch: qubes-vm-* provide qubes-core-agent-*

---

vm-init.d/qubes-updates-proxy

installed at same path on debian/redhat/fedora.
- follow-up to #596
- #157
- #155

tinyproxy: hardcode /usr/bin/tinyproxy path
