- misc/qubes.sudoers
Was reading up on Qubes and thought I could brush this part up a little. Hope no one's offended by the pedantry. :)
> Small language edit

- qubes-rpc/qvm-copy-to-vm.kde
- qubes-rpc/qvm-move-to-vm.kde
Closes https://github.com/QubesOS/qubes-issues/issues/1429
> Fall back to gnome utilities if kdialog not present

- misc/qubes.sudoers
Closes QubesOS/qubes-issues#2480
> Update Xen bug count in sudoers comment

- Makefile
- patches.debian/01_add_anacron.patch
- series-debian-vm.conf
- vm-systemd/anacron-resume.service.d/30_qubes.conf
- vm-systemd/anacron.service.d/30_qubes.conf
Closes QubesOS/qubes-issues#2109
> Apply constraints to anacron as well as cron in Debian and Ubuntu TemplateBasedVMs

- network/qubes-firewall
Closes QubesOS/qubes-issues#1555
> Reset iptables ACCEPT rule for updates proxy if service is running

- Makefile.builder
One of fixes for QubesOS/qubes-issues#2608
> Fix build for trusty - locales-all not available

- Makefile
- debian/qubes-core-agent.postinst
- vm-systemd/avahi-daemon.service.d/30_qubes.conf
- vm-systemd/exim4.service.d/30_qubes.conf
Closes QubesOS/qubes-issues#1928
> Stop unnecessary services from running in Debian

- doc/vm-tools/qvm-copy-to-vm.rst
- doc/vm-tools/qvm-open-in-dvm.rst
- doc/vm-tools/qvm-open-in-vm.rst
- doc/vm-tools/qvm-run.rst
Counterpart to https://github.com/QubesOS/qubes-core-admin/pull/94
> Remove dates from man pages (3/3)

- vm-systemd/bind-dirs.sh
Before, the script skipped none existing ro paths even if the path existed below /rw. This would require someone who wants to use bind-dirs only in TemplateBasedVM to ensure that the paths exist before the bind-dirs script gets called.
This patch changes this behavior so that if the path exists below /rw, it is ensured that an (empty) file/directory is present in ro (where the corresponding path from /rw is then bind mounted over).
Requires: Docs update. I can open a PR when this PRs looks good.
Fixes limitation: "Does not work if the file / folder in question does not already exist in the root image. I.e. a file that does not exist in the root image cannot be bind mounted in the TemplateBasedVM."
Example use case: https://github.com/debops/ansible-persistent_paths
Tested on: Qubes OS …
> bind-dirs: Create ro if bind target exists

- Makefile
- Makefile.builder
- debian/control
> Enable build for Zesty

- qubes-rpc/gui-fatal.h
- rpm_spec/core-agent.spec
Add CentOS template support and handle fallthrough for GCC7
> CentOS & Handle fallthrough

- misc/dnf-qubes-hooks.py
dnf-qubes-hooks: handle newer DNF >= 2.x
> dnf-qubes-hooks: handle newer DNF >= 2.x

- misc/upgrades-installed-check
Since I don't think it's possible to edit another user's pull request, this PR includes the cherry-picked commit from the original [pull request](https://github.com/QubesOS/qubes-core-agent-linux/pull/34) by @torrancew and a small fix.
> Add archlinux support to upgrade checker (resubmit)

- Makefile
- archlinux/PKGBUILD
- archlinux/PKGBUILD-qubes-noupgrade.conf
- archlinux/PKGBUILD-qubes-pacman-options.conf
- archlinux/PKGBUILD-qubes-repo-4.0.conf
- archlinux/PKGBUILD.install
- network/update-proxy-configs
- qrexec/Makefile
- qrexec/qrexec.pam.archlinux
- Picked @na-- commits
- Reviewed changes since 3.2 release
- Changed pam.d logic from using su to using qrexec
> Archlinux r4 template

- rpm_spec/core-vm.spec
> Add iptables dep to qubes-core-vm RPM spec

- qubesagent/firewall.py
- qubesagent/test_firewall.py
Fixes QubesOS/qubes-issues#3260
> call firewall-user-script at qubes-firewall service startup

- qubesagent/firewall.py
Enables easier configuration of firewall for vpn tunnels, etc.
> Add qubes-firewall.d feature

- misc/qubes-download-dom0-updates.sh
Add support for actions:
- list
- search
- reinstall
Fixes QubesOS/qubes-issues#3553
> Extend dom0 updates handling script on Debian

- misc/qubes-download-dom0-updates.sh
unless it's getting truncated somewhere along the way
> qubes-core-agent-linux: reinstal -> reinstall

- network/network-manager-prepare-conf-dir
- network/setup-ip
- network/vif-route-qubes
- qubesagent/firewall.py
- qubesagent/test_firewall.py
* IPv6: fix unreachable address (no IPv6 connectivity) reporting
* qubes-firewall: handle only outgoing traffic
Fixes QubesOS/qubes-issues#3644
> Network fixes

- misc/qubes-download-dom0-updates.sh
> Fix dom0 salt not being able to install packages when UpdateVM only has yum installed

- qrexec/qrexec-agent.c
- qrexec/qrexec-client-vm.c
- qubes-rpc/qopen-in-vm.c
- qubes-rpc/tar2qfile.c
https://github.com/QubesOS/qubes-issues/issues/3791
> Fix GCC8 warnings

- network/qubes-iptables
Move `--wait` to end of line because seconds not specified.
> Fixes issue #3939

- init/setup-rwdev.sh
As described in QubesOS/qubes-issues#3758, a VM may fail to start
if the private volume is large. This because the whole volume is read to
ensure it's empty (=all zeros).
This changes limits the check to the first 1 GiB of the private
volume. For additional safety, a scan with `blkid` is done.
Fixes https://github.com/QubesOS/qubes-issues/issues/3758
When creating the volume, in dom0, a special sequence could be written to the disk to mark it for formatting. Something like:
```
echo "This is a Qubes volume that needs to be formatted." >/dev/mapper/bla-bla--private
```
This could then be checked during VM startup:
```
marker="This is a Qubes volume that needs to be formatted."
if [ $(head -c ${marker[#]} "$dev") == "$marker" ]; then
echo "${marker//?/x}" >"$dev"
mkfs "$dev"
…
fi
```
Fixes …
> setup-rwdev.sh: Only check first 1 GiB for zeros

- archlinux/PKGBUILD
- archlinux/PKGBUILD.install
Complete fix of the issue https://github.com/QubesOS/qubes-issues/issues/1150 for archlinux
> archlinux: ensure /usr/local is present in fstab

- qubes-rpc/qvm-copy-to-vm.kde
- qubes-rpc/qvm-move-to-vm.kde
Fixes QubesOS/qubes-issues#4200
> R3.2 qvm-{copy,move}-to-vm.kde: '-inputbox' -> '--inputbox'

- Makefile.builder
Part of fix for QubesOS/qubes-issues#4439
> Fix build in 3.2 for bionic

- init/resize-rootfs-if-needed.sh
Originally came here just to s/dis/disk/, but rephrased while I was at it. I think the new one reads more clearly but happy to amend to just fix the typo.
> Rephrase comment

- init/functions
Hopefully this can be pushed as an update for Qubes 3.2 as well?
> Allow per-VM protected file list

- debian/control
- misc/qubes-r4.list.in
https://github.com/QubesOS/qubes-issues/issues/4415
> Switch to HTTPS

- init/resize-rootfs-if-needed.sh
The previous approach from #146 used `df` to get usable space and then added a fixed size to that number in order to account for filesystem overhead. However, at some point that stopped working for me. It appears that ext4 filesystem overhead can vary over time or because of other factors. (Certainly now that I think about it the old code would only work well for people with the exact same filesystem size as me.)
So the new approach is to just completely ignore what `df` tells us and instead go directly to the source: the filesystem's internal notion of exactly how much space it takes up. We use `dumpe2fs` to retrieve this information and calculate the on-disk size dynamically from that. Then we add the space that boot data takes up (unchanged), and we add 5MB padding because when I …
> Use dumpe2fs for filesystem size calculations

- vm-systemd/75-qubes-vm.preset
> Disable useless Xen services in Qubes VM since we use upstream pacakge

- network/vif-route-qubes
Example:
/rw/config/network-hooks.d/test.sh
\#!/bin/bash
command="$1"
vif="$2"
ip="$3"
if [ "$ip" == '10.137.0.100' ]; then
case "$command" in
online)
ip route add 192.168.0.100 via 10.137.0.100
;;
offline)
ip route del 192.168.0.100
;;
esac
fi
> Handle network hooks located in /rw/config/network-hooks.d

- init/functions
- network/network-manager-prepare-conf-dir
- network/setup-ip
- network/udev-qubes-network.rules
- vm-systemd/misc-post.sh
> Refactor and handle new network qubesdb configuration

- debian/qubes-core-agent.preinst
https://github.com/QubesOS/qubes-issues/issues/1130
This makes this easier to review, discuss, modify.
> use long options rather than short options

- misc/qubes-download-dom0-updates.sh
This pull request is intended to be merged together with https://github.com/QubesOS/qubes-core-admin-linux/pull/50
(This commit is applicable to the release4.0 branch as well.)
> dom0-updates: Quote arguments

- misc/dnf-qubes-hooks.py
- misc/qubes-download-dom0-updates.sh
- report to dom0 when no more updates are available at the end of dnf update call
- fix dom0 updates download on Debian VM
QubesOS/qubes-issues#2009
> Updates related fixes

- misc/fstab
implements https://github.com/QubesOS/qubes-issues/issues/5263
> Mount /rw and /home with nosuid + nodev

- network/qubes-fix-nm-conf.sh
Closes QubesOS/qubes-issues#4828
> NetworkManager config - Add dns=default

- misc/qubes-download-dom0-updates.sh
This PR implements signature verification of downloaded RPMs in the UpdateVM.  The documentation on secure updates for dom0 mentions that the UpdateVM is considered [untrusted][1], and that dom0 is responsible for verifying package signatures.
However, I think it makes sense to designate a (semi-)trusted domU as the UpdateVM; especially with how easy it is to create new guests in Qubes.
By verifying package signatures on a (semi-)trusted domU, an attacker is put in a position of having to find an exploitable condition on **both** domU and dom0 in order to compromise the entire system through software updates.
Ideally, either domU or dom0 would use a different implementation for package verification (e.g. with a minimal RPM header parser and an alternative PGP implementation) to further …
> qubes-download-dom0-updates: verify package signatures

- misc/grub.qubes
https://github.com/QubesOS/qubes-issues/issues/5490#issuecomment-562263712
> console=hvc0 must be last

- qubes-rpc/qfile-unpacker.c
Previously, both file path and username were hardcoded.
Fixes QubesOS/qubes-issues#5385.
> Make the file copy operation respect default_user

- misc/qubes-run-terminal
Fixes QubesOS/qubes-issues#4606.
> qubes-run-terminal: use gnome-terminal --wait, if supported

- debian/qubes-core-agent.install
- qubes-rpc/Makefile
- qubes-rpc/post-install.d/10-qubes-core-agent-features.sh
- qubes-rpc/qubes.VMExec
- qubes-rpc/qubes.VMExecGUI.config
- qubesagent/test_vmexec.py
- qubesagent/vmexec.py
- rpm_spec/core-agent.spec.in
- setup.py
https://github.com/QubesOS/qubes-issues/issues/4850
> Add qubes.VMExec call, for running a single command

- Makefile
- applications-dropins/Makefile
- applications-dropins/README.txt
- applications-dropins/org.gnome.Terminal.desktop
- archlinux/PKGBUILD
- debian/qubes-core-agent.install
- misc/qubes-run-gnome-terminal
- misc/qubes-run-terminal
- misc/qubes-session-autostart
- qubesagent/test_xdg.py
- qubesagent/xdg.py
- rpm_spec/core-agent.spec.in
Fixes QubesOS/qubes-issues#2581.
> Add override from gnome-terminal desktop shortcut

- rpm_spec/core-agent.spec.in
To be backported in release4.0 branch.
> spec: replace python3 by python%{python3_pkgversion}

- archlinux/PKGBUILD
python2 is being removed and python3-YYYY is being renamed to python-YYYY.
> fix https://github.com/QubesOS/qubes-issues/issues/5619

- vm-systemd/75-qubes-vm.preset
Added services to preset file.
Closes QubesOS/qubes-issues#5206
> Disable unnecessary services in Debian

- vm-systemd/qubes-sysinit.sh
https://github.com/QubesOS/qubes-issues/issues/5662
https://github.com/QubesOS/qubes-issues/issues/833
> qubes-sysinit: set GUI_OPTS in gui-agent-linux

- rpm_spec/core-agent.spec.in
> spec: fix missing python3 gi module

- debian/control
- rpm_spec/core-agent.spec.in
> Fix missing dependency for managing Network-Manager in active user session

- package-managers/dnf-qubes-hooks.py
Fix it for DNF 4+, remove workaround for https://bugzilla.redhat.com/1650446
> Fix available updates notification at the end of dnf

- debian/qubes-core-agent.install
- qubes-rpc/Makefile
- qubes-rpc/qfile-unpacker.c
- qubes-rpc/qubes.RegisterBackupLocation
- qubes-rpc/qubes.RestoreById
- qubes-rpc/tar2qfile.c
- rpm_spec/core-agent.spec.in
Changes for paranoid restore mode
- extra qrexec services
- extend qfile-unpacker for disk space monitoring and custom target dir
Depends on QubesOS/qubes-linux-utils#43
QubesOS/qubes-issues#5310
QubesOS/qubes-issues#4791
QubesOS/qubes-issues#930
> Paranoid restore

- qubes-rpc/post-install.d/10-qubes-core-agent-features.sh
https://github.com/QubesOS/qubes-issues/issues/4088
> Advertise apparmor support

- debian/qubes-core-agent.install
- qubes-rpc/Makefile
- qubes-rpc/qubes.TemplateDownload
- qubes-rpc/qubes.TemplateSearch
- qubes-rpc/qvm-template-repo-query
- rpm_spec/core-agent.spec.in
Discussions: <https://groups.google.com/forum/#!topic/qubes-devel/2XaMP4Us3kg>
Design doc: <https://gist.github.com/WillyPillow/b8a643ddbd9235a97bc187e6e44b16e4>
Major changes:
- New `qubes.Template{Search,Download}` qrexec calls for interaction with repos.
> Support for qvm-template (qubes.Template{Search,Download} calls)

- vm-systemd/75-qubes-vm.preset
QubesOS/qubes-issues/issues/4186
> vm-systemd: enable dummy modules and psu client

- archlinux/PKGBUILD
- archlinux/PKGBUILD.install
https://github.com/QubesOS/qubes-issues/issues/6028
> Fix archlinux packaging

- package-managers/Makefile
- rpm_spec/core-agent.spec.in
> Fix centos8 dnf-plugin

- network/setup-ip
- network/vif-qubes-nat.sh
- network/vif-route-qubes
This fixes IPv6 on OpenBSD HVMs, and probably fixes it on Arch HVMs (which run systemd-networkd).
> Add permanent neighbor entries

- debian/qubes-core-agent-networking.install
- init/functions
- network/ip6tables-enabled
- network/setup-ip
- network/udev-qubes-network.rules
- rpm_spec/core-agent.spec.in
- vm-systemd/75-qubes-vm.preset
- vm-systemd/NetworkManager.service.d/30_qubes.conf
- vm-systemd/misc-post.sh
- vm-systemd/network-proxy-stop.sh
- vm-systemd/network-uplink-wait.sh
- vm-systemd/qubes-early-vm-config.service
- vm-systemd/qubes-network-uplink.service
- vm-systemd/qubes-network-uplink@.service
- vm-systemd/qubes-network.service
Adjust network start/stop ordering and firewall. See individual commit messages
for details.
QubesOS/qubes-issues#5576
Fixes QubesOS/qubes-issues#5570
Fixes QubesOS/qubes-issues#5599
Fixes QubesOS/qubes-issues#5886
> Various network related fixes

- package-managers/upgrades-installed-check
- package-managers/yum-qubes-r4.repo.in
Fixes https://github.com/QubesOS/qubes-issues/issues/6177
> Metadata is now signed

- passwordless-root/polkit-1-qubes-allow-all.rules
- passwordless-root/qubes.sudoers
See individual commit messages for details.
> Various passwordless root improvements

- package-managers/qubes-download-dom0-updates.sh
- qubes-rpc/qvm-copy
See individual commit messages for details.
> Various improvements

- archlinux/PKGBUILD
This is necessary for in-VM kernels to work.
> Install grub.qubes on Arch

- doc/vm-tools/qvm-copy.rst
rename qvm-copy-to-vm to qvm-copy
> addresses https://github.com/QubesOS/qubes-issues/issues/6374

- Makefile
- autostart-dropins/xfce4-notifyd.desktop
- debian/qubes-core-agent.install
- vm-systemd/haveged.service
- fix xfce4-notifyd not starting
- drop unneded now workaround for haveged service
> Misc startup fixes

- qubes-rpc/nautilus/qvm_copy_nautilus.py
> Fix typo in qvm_copy_nautilus.py

- misc/qvm-features-request
- package-managers/dnf-qubes-hooks.py
Needed for QubesOS/qubes-issues#4867
> Don't try to execute qrexec if service is not running

- qubes-rpc/thunar/qvm-actions.sh
- rpm_spec/core-agent.spec.in
This also fixes https://github.com/QubesOS/qubes-issues/issues/6612
> Add progress bar to Thunar actions

- qubes-rpc/kde/qvm-copy.desktop
Addresses QubesOS/qubes-issues#1040
> Change language for qvm-copy in KDE

- qubesagent/xdg.py
Fedora has patched[1] glib to communicate with systemd over dbus even for
apps without DBusActivatable=true. This requires event loop being
initialized, otherwise starting an application will hang.
[1] https://src.fedoraproject.org/rpms/glib2/blob/f34/f/0002-gdesktopappinfo-Move-launched-applications-into-tran.patch
QubesOS/qubes-issues#6568
> qubes-desktop-run: setup glib event loop for non-dbus apps too

- qubes-rpc/qvm-copy
Also perform a bunch of cleanups.
> qvm-{copy,move}: accept -- as end of options

- qubesagent/firewall.py
Manually tested in debian-10 and fedora-33.
Fixes QubesOS/qubes-issues#6658
> firewall: make notify-send work

- network/30-qubes-external-ip
- package-managers/upgrades-installed-check
- qubes-rpc/prepare-suspend
- qubes-rpc/qubes.RegisterBackupLocation
- qubes-rpc/qubes.Restore
- qubes-rpc/qubes.RestoreById
- qubes-rpc/qvm-open-in-vm
> Fixes for qubes.RestoreById and few more

- config-overrides/Makefile
- config-overrides/profile.d_qubes_disable_lesspipe.sh
- debian/qubes-core-agent.install
- rpm_spec/core-agent.spec.in
> Disable LESSOPEN and LESSCLOSE

- qubes-rpc/qubes.Restore
this is a minor cosmetic fix related to https://github.com/QubesOS/qubes-core-admin-client/pull/182
references QubesOS/qubes-issues#3446
> Better message on backup restore data load fail

- debian/control
- debian/qubes-core-agent-dom0-updates.install
- debian/qubes-core-agent.install
- package-managers/Makefile
- package-managers/dnf-plugin-download.py
- package-managers/dnf-qubes-hooks.py
- qubes-rpc/qvm-template-repo-query
- rpm_spec/core-agent.spec.in
Work in progress (see individual commit messages).
QubesOS/qubes-issues#6985
> dnf related fixes

- autostart-dropins/nm-applet.desktop
- network/show-hide-nm-applet.desktop
- network/show-hide-nm-applet.sh
> Reduce memory usage

- package-managers/dnf-qubes-hooks.py
Fixes https://github.com/QubesOS/qubes-issues/issues/7083
> dnf: drop old dnf support

- debian/qubes-core-agent-thunar.postrm
Otherwise each update of qubes-core-agent-thunar will add another set of actions to `/etc/xdg/Thunar/uca.xml` instead of overwriting them
> Fix duplicate actions in Thunar

- qubes-rpc/suspend-post.d/qvm-sync-clock.sh
fixes https://github.com/QubesOS/qubes-issues/issues/7265
> use common entry point for qvm-sync-clock

- qubes-rpc/gui-fatal.c
- qubes-rpc/qvm-copy
- qubes-rpc/qvm-copy-to-vm.gnome
`kdialog` or `zenity` block the underlying process until we quit the popup. Either on server or automated workflows, we don't need GUI notifications that a requested file is missing.
> qfile-agent: display GUI message only on PROGRESS_TYPE=gui

- package-managers/qubes-download-dom0-updates.sh
partial fix for https://github.com/QubesOS/qubes-issues/issues/7346
> add support for alternate rpmdb pathes

- qubes-rpc/qubes-sync-clock
- qubes-rpc/qubes.GetDate
- qubes-rpc/qvm-sync-clock
- vm-systemd/qubes-sync-time.service
Requires QubesOS/qubes-core-admin#442 to be installed in dom0.
Fixes QubesOS/qubes-issues#7081.
> Support nanosecond precision for dates

- debian/qubes-core-agent.install
- package-managers/Makefile
- package-managers/apt-qubes-r4.list.in
Closes QubesOS/qubes-issues#7271
> Cohere with Debian guidance on 3rd party repos

- qubesagent/firewall.py
- qubesagent/test_firewall.py
Previously adding a firewall rule didn't close already established connections: https://github.com/QubesOS/qubes-issues/issues/4141
> Add purging of no longer allowed connections from conntrack

- archlinux/PKGBUILD
- debian/control
- debian/qubes-core-agent.links
- misc/data-dirs
- qubes-rpc/qubes.GetImageRGBA
- rpm_spec/core-agent.spec.in
https://github.com/QubesOS/qubes-issues/issues/5009
> Replace ImageMagick with GraphicsMagick

- Makefile
- debian/qubes-core-agent-networking.install
- network/80-qubes.conf
- network/81-qubes.conf.optional
- network/setup-ip
- network/vif-route-qubes
- rpm_spec/core-agent.spec.in
This is done via various sysctls.
> Harden network interfaces before enabling them

- package-managers/dnf-plugin-downloadurl.py
Fix typo, use correct variable.
> qvm-template: fix dnf download plugin

- qubes-rpc/qvm-copy
Fixes: QubesOS/qubes-issues#8023
> Add -h and --help to qvm-copy

- selinux/qubes-misc.te
Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2185490
QubesOS/qubes-issues#8069
> Workaround Fedora selinux preventing shutdown

- vm-systemd/qubes-antispoof.service
The Before= should be in the Unit section, not Service one.
> Fix qubes-antispoof.service

- passwordless-root/qubes.sudoers
Fixes QubesOS/qubes-issues#7237
Replaces #449
> Remove outdated comment

- .gitlab-ci.yml
- qubes-rpc/qfile-agent.c
- qubesagent/test_tools.py
- rpm_spec/core-agent.spec.in
- run-tests
Fixes QubesOS/qubes-issues#8516
> qfile-agent: use a dirfd instead of getcwd()

- qubes-rpc/qfile-agent.c
- qubes-rpc/qvm-copy
- qubes-rpc/qvm-copy-to-vm.gnome
Fixes QubesOS/qubes-issues#1519
> Filecopy progress fixes

- misc/qvm-features-request
Fixes QubesOS/qubes-issues#8609
Fixes QubesOS/qubes-issues#4469
> Improve error handling in qvm-features-request

- Makefile
- debian/qubes-core-agent-passwordless-root.install
- debian/qubes-core-agent.install
- package-managers/Makefile
- passwordless-root/Makefile
- passwordless-root/polkit-1-qubes-allow-all.pkla
- rpm_spec/core-agent.spec.in
- vm-systemd/sysinit.target.d/30_qubes.conf
> openSUSE packaging

- doc/vm-tools/qvm-copy.rst
Improve information for qvm-copy.
fixes QubesOS/qubes-issues#6374
> Minor docs fix

- network/qvm-connect-tcp
Fixes: https://github.com/QubesOS/qubes-issues/issues/8923
> Skip sudo for unprivileged ports binds

- network/qubes-nmhook
Re-submitting as I closed the original PR by mistake.
> #8991 - support for the dhcp4-change event in qubes-nmhook

- qubes-rpc/post-install.d/10-qubes-core-agent-features.sh
Send distribution, version and EOL data to dom0.
Fixes QubesOS/qubes-issues#8725
> Tell dom0 about basic distribution metadata

- package-managers/upgrades-status-notify
- vm-systemd/qubes-update-check.service
fixes https://github.com/QubesOS/qubes-issues/issues/1066
> fix: do not run package manager update command every time a package gets installed in App Qube

- vm-systemd/qubes-sysinit.sh
Fixes: https://github.com/QubesOS/qubes-issues/issues/9268
For: https://github.com/QubesOS/qubes-core-admin-client/pull/294
For: https://github.com/QubesOS/qubes-gui-agent-linux/pull/214
> Enable software-rendering by default

- app-menu/qvm-open-in-dvm.desktop
Fixes https://github.com/QubesOS/qubes-issues/issues/7210
> Add NoDisplay=true

- debian/control
Fixes QubesOS/qubes-issues/issues/9343
> Include distro-info-data

- doc/Makefile
- doc/vm-tools/qvm-move.rst
fixes: https://github.com/QubesOS/qubes-issues/issues/8023
> Manual for qvm-move(1)

- qubes-rpc/qubes.GetImageRGBA
Fixes https://github.com/QubesOS/qubes-issues/issues/9378
> Fix warped SVG icons, ensure correct rasterized size

- qubes-rpc/nautilus/qvm_copy_nautilus.py
- qubes-rpc/nautilus/qvm_dvm_nautilus.py
- qubes-rpc/nautilus/qvm_move_nautilus.py
fixes: https://github.com/QubesOS/qubes-issues/issues/8589
> Allow recent:/// in Nautilus for Copy/Move/Open

- qubes-rpc/post-install.d/10-qubes-core-agent-features.sh
- vm-systemd/misc-post-stop.sh
resolves QubesOS/qubes-issues#8307
>  Misc-post-stop: remove unused QubesIncoming

- network/vif-qubes-nat.sh
- network/vif-route-qubes
> Replace test and [ with bash's [[

- qubes-rpc/tar2qfile.c
tar2qfile had some bugs.  Fix them.
> Harden tar2qfile

- package-managers/qubes-download-dom0-updates.sh
resolves: https://github.com/QubesOS/qubes-issues/issues/9958
> Allow `qubes-dom0-update --action=download`

- rpm_spec/core-agent.spec.in
> rpm spec file cleanup
